parameters:
    shipping.shippingapi.class: Hanzo\Bundle\ShippingBundle\ShippingApi

services:
    shipping.shippingapi:
        class: %shipping.shippingapi.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     shipping.shippingapi 
            parameters:  ~
            class:       %shipping.shippingapi.class%
