parameters:
#    shipping.example.class: Hanzo\Bundle\ShippingBundle\Example

services:
#    shipping.example:
#        class: %shipping.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
