framework:
    default_locale: de_AT
    session:
        cookie_path: '/de_AT'

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:     %database_at_driver%
                user:       %database_at_user%
                password:   %database_at_password%
                dsn:        mysql:host=%database_at_host%;dbname=%database_at_name%
                options:    {}
                attributes: {}

cms:
    frontpage: 538

consignor:
    shipment_server:
        options:
              actor: 6202
              product_concept_id: 94
              service_id: 9024
              key: PompDeluxDE
              to_address:
                  name: "POMPdeLUX De GmbH"
                  address_line_1: "Dammtorstraße 12"
                  postal_code: "20354"
                  city: "Hamburg Ust-IdNr."
                  country_iso2: DE
                  email: mailde@pompdelux.com
                  phone: "040-3571 5072"

