framework:
    default_locale: de_AT
    session:
        cookie_path: '/de_AT'

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:     %database_at_driver%
                user:       %database_at_user%
                password:   %database_at_password%
                dsn:        mysql:host=%database_at_host%;dbname=%database_at_name%
                options:    {}
                attributes: {}

cms:
    frontpage: 538

consignor:
    shipment_server: ~
