framework:
    default_locale: de_DE
    session:
        cookie_path: '/de_DE'

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:     %database_de_driver%
                user:       %database_de_user%
                password:   %database_de_password%
                dsn:        mysql:host=%database_de_host%;dbname=%database_de_name%
                options:    {}
                attributes: {}

cms:
    frontpage: 538

account:
    consignor:
        actor_id: 69
