framework:
    default_locale: de_DE
    session:
        cookie_path: '/de_DE'

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:     %database_de_driver%
                user:       %database_de_user%
                password:   %database_de_password%
                dsn:        mysql:host=%database_de_host%;dbname=%database_de_name%
                options:    {}
                attributes: {}

cms:
    frontpage: 538


account:
    consignor:
        actor_id: 69

consignor:
    shipment_server:
        options:
              actor: 6202
              product_concept_id: 94
              service_id: 9024
              key: PompDeluxDE
              to_address:
                  name: "POMPdeLUX De GmbH"
                  address_line_1: "Dammtorstraße 12"
                  postal_code: "20354"
                  city: "Hamburg Ust-IdNr."
                  country_iso2: DE
                  email: mailde@pompdelux.com
                  phone: "040-3571 5072"

