framework:
    default_locale: da_DK
    session:
        cookie_path: '/da_DK'

# Needed so we can switch connections in admin
propel:
    dbal:
        default_connection: pdldbdk1
        connections:
            pdldbdk1:
                driver:               %database_driver%
                user:                 %dev_dk_database_user%
                password:             %dev_dk_database_password%
                dsn:                  mysql:host=%dev_dk_database_host%;dbname=%dev_dk_database_name%;charset=utf8
                options:              {}
                attributes:           {}
# ------------------------------------------------------------------------------------------
# we no longer use slaves, if we ever need to again - this is the block to enable/duplicate
# ------------------------------------------------------------------------------------------
#                slaves:
#                    pdldbdk2:
#                        user:         %dev_dk_database_slave_1_user%
#                        password:     %dev_dk_database_slave_1_password%
#                        dsn:          %dev_dk_database_slave_1_dsn%
# ------------------------------------------------------------------------------------------
            pdldbde1:
                driver:               %database_driver%
                user:                 %dev_de_database_user%
                password:             %dev_de_database_password%
                dsn:                  mysql:host=%dev_de_database_host%;dbname=%dev_de_database_name%;charset=utf8
                options:              {}
                attributes:           {}
            pdldbfi1:
                driver:               %database_driver%
                user:                 %dev_fi_database_user%
                password:             %dev_fi_database_password%
                dsn:                  mysql:host=%dev_fi_database_host%;dbname=%dev_fi_database_name%;charset=utf8
                options:              {}
                attributes:           {}
            pdldbnl1:
                driver:               %database_driver%
                user:                 %dev_nl_database_user%
                password:             %dev_nl_database_password%
                dsn:                  mysql:host=%dev_nl_database_host%;dbname=%dev_nl_database_name%;charset=utf8
                options:              {}
                attributes:           {}
            pdldbno1:
                driver:               %database_driver%
                user:                 %dev_no_database_user%
                password:             %dev_no_database_password%
                dsn:                  mysql:host=%dev_no_database_host%;dbname=%dev_no_database_name%;charset=utf8
                options:              {}
                attributes:           {}
            pdldbse1:
                driver:               %database_driver%
                user:                 %dev_se_database_user%
                password:             %dev_se_database_password%
                dsn:                  mysql:host=%dev_se_database_host%;dbname=%dev_se_database_name%;charset=utf8
                options:              {}
                attributes:           {}
            pdldbat1:
                driver:               %database_driver%
                user:                 %dev_at_database_user%
                password:             %dev_at_database_password%
                dsn:                  mysql:host=%dev_at_database_host%;dbname=%dev_at_database_name%;charset=utf8
                options:              {}
                attributes:           {}
            pdldbch1:
                driver:               %database_driver%
                user:                 %dev_ch_database_user%
                password:             %dev_ch_database_password%
                dsn:                  mysql:host=%dev_ch_database_host%;dbname=%dev_ch_database_name%;charset=utf8
                options:              {}
                attributes:           {}

account:
    consignor:
        actor_id: 63

consignor:
    shipment_server:
        options:
              actor: 6197
              product_concept_id: 94
              service_id:
              service_id: 9024
              key: PompDeluxDK
              to_address:
                  name: "POMPdeLUX ApS"
                  address_line_1: "Møgelhøj 8"
                  postal_code: "8520"
                  city: "Lystrup"
                  country_iso2: DK
                  email: mail@pompdelux.dk
                  phone: "+45 8678 7871"

google:
    tag_manager:
        gtm_id:             "GTM-TDVFG4"
        enabled_datalayers:
            - Ecommerce
            - Remarketing
        addwords:
            conversion_id: 000000001
            conversion_label: Dev
