framework:
    default_locale: fi_FI
    session:
        cookie_path: '/fi_FI'

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:     %database_fi_driver%
                user:       %database_fi_user%
                password:   %database_fi_password%
                dsn:        mysql:host=%database_fi_host%;dbname=%database_fi_name%
                options:    {}
                attributes: {}

cms:
    frontpage: 538

account:
    consignor:
        actor_id: 68

consignor:
    shipment_server:
        options:
              actor: 6201
              product_concept_id: 882
              service_id: 9065
              key: PompDeluxFI
              to_address:
                  name: "POMPdeLUX ApS"
                  address_line_1: "Møgelhøj 8"
                  postal_code: "8520"
                  city: "Lystrup"
                  country_iso2: DK
                  email: mailfi@pompdelux.com
                  phone: "09-34870870"
