framework:
    default_locale: sv_SE
    session:
        cookie_path: '/sv_SE'

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:     %database_se_driver%
                user:       %database_se_user%
                password:   %database_se_password%
                dsn:        mysql:host=%database_se_host%;dbname=%database_se_name%
                options:    {}
                attributes: {}

cms:
    frontpage: 540
