framework:
    router:
        resource:           "%kernel.root_dir%/config/routing_dev.yml"
    profiler:
        only_exceptions:    false

web_profiler:
    toolbar:                true
    intercept_redirects:    false
    # verbose:                true

monolog:
    handlers:
        main:
            type:           stream
            path:           %kernel.logs_dir%/%kernel.environment%.log
            level:          debug
        # logstash:
        #     type:           socket
        #     connection_string: tcp://logstash.bellcom.dk:5544
        #     level:          debug
        firephp:
            type:           firephp
            level:          info

assetic:
    use_controller:         true

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:     %database_driver%
                user:       %database_user%
                password:   %database_password%
                dsn:        mysql:host=%database_host%;dbname=%database_name%
                options:    {}
                attributes: {}
            # use for testing replications or other multi db stuff
            # please do not commit with this block activated.
            # replicated:
            #     driver:               %database_driver%
            #     user:                 %database_user%
            #     password:             %database_password%
            #     dsn:                  mysql:host=%database_host%;dbname=%database_name%_replicated
            #     options:              {}
            #     attributes:           {}

    build_properties:
      propel.project: '%database_name%'
      propel.addValidators: all
      propel.namespace.autoPackage: true

cms:
    frontpage: 556

ax:
    log_requests: true
