framework:
    router:
        resource:           "%kernel.root_dir%/config/routing_dev.yml"
    profiler:
        only_exceptions:    false

# always send mails to a bellcom address
swiftmailer:
    delivery_address: pdl@bellcom.dk

web_profiler:
    toolbar:                true
    intercept_redirects:    false
    # verbose:                true

monolog:
    handlers:
        main:
            type:           stream
            path:           %kernel.logs_dir%/%kernel.environment%.log
            level:          debug
        firephp:
            type:           firephp
            level:          info

propel:
    dbal:
        classname: Glorpen\Propel\PropelBundle\Connection\EventDebugPDO
# -----------------------------------------------------------
# un: 2016.02.02
#
# removed due to the fact that the default connection
# "default" overrides the ones set in the override files...
#
# NOTE: you now have to have a propel connect block in
# your _locale_xx.yml file pr. language you which to support!
# -----------------------------------------------------------
#        default_connection: default
#        connections:
#            default:
#                driver:     %database_driver%
#                user:       %database_user%
#                password:   %database_password%
#                dsn:        mysql:host=%database_host%;dbname=%database_name%;charset=utf8
#                options:    {}
#                attributes: {}
# -----------------------------------------------------------
            # use for testing replications or other multi db stuff
            # please do not commit with this block activated.
            # replicated:
            #     driver:               %database_driver%
            #     user:                 %database_user%
            #     password:             %database_password%
            #     dsn:                  mysql:host=%database_host%;dbname=%database_name%_replicated
            #     options:              {}
            #     attributes:           {}

    build_properties:
        propel.project: '%database_name%'
        propel.addValidators: all
        propel.namespace.autoPackage: true

cms:
    frontpage: 556

ax:
    log_requests: true

consignor:
    shipment_server:
        endpoint: "https://www.shipmentserver.com/ship/ShipmentServerModule.dll"

stock:
    warehouses:
        main:
            - da_DK
            - de_CH
            - fi_FI
            - sv_SE
            - en_GB
        norway:
            - nb_NO
        eu_south:
            - de_AT
            - de_DE
            - nl_NL
    connection_map:
        pdldbdk1: main
        pdldbfi1: main
        pdldbse1: main
        pdldbch1: main
        pdldbno1: norway
        pdldbde1: eu_south
        pdldbnl1: eu_south
        pdldbat1: eu_south
