framework:
    router:
        resource:           "%kernel.root_dir%/config/routing_dev.yml"
    profiler:
        only_exceptions:    false


propel:
    dbal:
        default_connection: pdldbdk1
        connections:
            pdldbdk1:
                driver:               %database_driver%
                user:                 %dev_dk_database_user%
                password:             %dev_dk_database_password%
                dsn:                  mysql:host=%dev_dk_database_host%;dbname=%dev_dk_database_name%;charset=utf8
                options:              {}
                attributes:           {}
# ------------------------------------------------------------------------------------------
# we no longer use slaves, if we ever need to again - this is the block to enable/duplicate
# ------------------------------------------------------------------------------------------
#                slaves:
#                    pdldbdk2:
#                        user:         %dev_dk_database_slave_1_user%
#                        password:     %dev_dk_database_slave_1_password%
#                        dsn:          %dev_dk_database_slave_1_dsn%
# ------------------------------------------------------------------------------------------
#            pdldbde1:
#                driver:               %database_driver%
#                user:                 %dev_de_database_user%
#                password:             %dev_de_database_password%
#                dsn:                  mysql:host=%dev_de_database_host%;dbname=%dev_de_database_name%
#                options:              {}
#                attributes:           {}
#            pdldbfi1:
#                driver:               %database_driver%
#                user:                 %dev_fi_database_user%
#                password:             %dev_fi_database_password%
#                dsn:                  mysql:host=%dev_fi_database_host%;dbname=%dev_fi_database_name%
#                options:              {}
#                attributes:           {}
            pdldbnl1:
                driver:               %database_driver%
                user:                 %dev_nl_database_user%
                password:             %dev_nl_database_password%
                dsn:                  mysql:host=%dev_nl_database_host%;dbname=%dev_nl_database_name%;charset=utf8
                options:              {}
                attributes:           {}
#            pdldbno1:
#                driver:               %database_driver%
#                user:                 %dev_no_database_user%
#                password:             %dev_no_database_password%
#                dsn:                  mysql:host=%dev_no_database_host%;dbname=%dev_no_database_name%
#                options:              {}
#                attributes:           {}
#            pdldbse1:
#                driver:               %database_driver%
#                user:                 %dev_se_database_user%
#                password:             %dev_se_database_password%
#                dsn:                  mysql:host=%dev_se_database_host%;dbname=%dev_se_database_name%
#                options:              {}
#                attributes:           {}
#            pdldbat1:
#                driver:               %database_driver%
#                user:                 %dev_at_database_user%
#                password:             %dev_at_database_password%
#                dsn:                  mysql:host=%dev_at_database_host%;dbname=%dev_at_database_name%
#                options:              {}
#                attributes:           {}
#            pdldbch1:
#                driver:               %database_driver%
#                user:                 %dev_ch_database_user%
#                password:             %dev_ch_database_password%
#                dsn:                  mysql:host=%dev_ch_database_host%;dbname=%dev_ch_database_name%
#                options:              {}
#                attributes:           {}

# always send mails to a bellcom address
swiftmailer:
    delivery_address: pdl@bellcom.dk

web_profiler:
    toolbar:                true
    intercept_redirects:    false
    # verbose:                true

monolog:
    handlers:
        main:
            type:           stream
            path:           %kernel.logs_dir%/%kernel.environment%.log
            level:          debug
        firephp:
            type:           firephp
            level:          info

cms:
    frontpage: 556

ax:
    log_requests: true

consignor:
    shipment_server:
        endpoint: "https://www.shipmentserver.com/ship/ShipmentServerModule.dll"

