PaymentBundle_process:
    pattern:  /payment/process/{order_id}
    defaults: { _controller: PaymentBundle:Default:process }
    requirements:
        page:  \d+

PaymentBundle_dibs_callback:
    pattern:  /payment/dibs/callback
    defaults: { _controller: PaymentBundle:Dibs:callback }
    requirements:
        _method: POST

PaymentBundle_dibs_form_update:
    pattern:  /payment/dibs/formupdate
    defaults: { _controller: PaymentBundle:Dibs:block}
    requirements: { _format: (xml|json), _method: POST }

PaymentBundle_dibs_cancel:
    pattern:  /payment/dibs/cancel
    defaults: { _controller: PaymentBundle:Dibs:cancel }

PaymentBundle_gothia_payment:
    pattern:  /payment/gothia
    defaults: { _controller: PaymentBundle:Gothia:payment }

PaymentBundle_gothia_payment_test:
    pattern:  /payment/gothia/test
    defaults: { _controller: PaymentBundle:Gothia:test }

PaymentBundle_gothia_payment_checkcustomer:
    pattern:  /payment/gothia/checkcustomer
    defaults: { _controller: PaymentBundle:Gothia:checkCustomer, _format: json }
    requirements: { _format: (xml|json), _method: POST }

PaymentBundle_gothia_payment_confirm:
    pattern:  /payment/gothia/confirm
    defaults: { _controller: PaymentBundle:Gothia:confirm, _format: json }
    requirements: { _format: (xml|json), _method: POST }

_paybybill_callback:
    pattern:  /payment/paybybill/callback
    defaults: { _controller: PaymentBundle:PayByBill:callback }

_order_state_check:
    pattern: /payment/dibs/state-check
    defaults: { _controller: PaymentBundle:Dibs:stateCheck, _format: json }
    requirements: { _format: (xml|json), _method: POST }
