# DIBS }-------------------------
PaymentBundle_dibs_process:
    pattern:  /payment/dibs/process/{order_id}
    defaults: { _controller: PaymentBundle:Dibs:process }
    requirements:
        order_id:  \d+

PaymentBundle_dibs_callback:
    pattern:  /payment/dibs/callback
    defaults: { _controller: PaymentBundle:Dibs:callback }
    requirements:
        _method: POST

PaymentBundle_dibs_form_update:
    pattern:  /payment/dibs/formupdate
    defaults: { _controller: PaymentBundle:Dibs:block}
    requirements: { _format: (xml|json), _method: POST }

PaymentBundle_dibs_cancel:
    pattern:  /payment/dibs/cancel
    defaults: { _controller: PaymentBundle:Dibs:cancel }

_order_state_check:
    pattern: /payment/dibs/state-check
    defaults: { _controller: PaymentBundle:Dibs:stateCheck, _format: json }
    requirements: { _format: (xml|json), _method: POST }

# GOTHIA }-------------------------
PaymentBundle_gothia_process:
    pattern:  /payment/gothia/process
    defaults: { _controller: PaymentBundle:Gothia:process }

PaymentBundle_gothia_payment:
    pattern:  /payment/gothia
    defaults: { _controller: PaymentBundle:Gothia:payment }

PaymentBundle_gothia_payment_test:
    pattern:  /payment/gothia/test
    defaults: { _controller: PaymentBundle:Gothia:test }

PaymentBundle_gothia_payment_checkcustomer:
    pattern:  /payment/gothia/checkcustomer
    defaults: { _controller: PaymentBundle:Gothia:checkCustomer, _format: json }
    requirements: { _format: (xml|json), _method: POST }

PaymentBundle_gothia_payment_confirm:
    pattern:  /payment/gothia/confirm
    defaults: { _controller: PaymentBundle:Gothia:confirm, _format: json }
    requirements: { _format: (xml|json), _method: POST }

# COD }-------------------------
_paybybill_callback:
    pattern:  /payment/paybybill/callback
    defaults: { _controller: PaymentBundle:PayByBill:callback }


_payment_set_method:
    pattern: /checkout/payment/set/method
    defaults:
        _controller: PaymentBundle:Default:setMethod

# ALL }-------------------------
_process_payment:
    pattern: /checkout/payment/process
    defaults:
        _controller: PaymentBundle:Default:getProcessButton
