parameters:
    payment.dibsapi.class: Hanzo\Bundle\PaymentBundle\Methods\Dibs\DibsApi
    payment.gothiaapi.class: Hanzo\Bundle\PaymentBundle\Methods\Gothia\GothiaApi
    payment.paybybill.class: Hanzo\Bundle\PaymentBundle\Methods\PayByBill\PayByBillApi
    payment.coupon.class: Hanzo\Bundle\PaymentBundle\Methods\Coupon\CouponApi
    payment.pensio.class: Hanzo\Bundle\PaymentBundle\Methods\Pensio\PensioApi

services:
    payment.dibsapi:
        class:           %payment.dibsapi.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     dibsapi
            parameters:  [@router]
            class:       %payment.dibsapi.class%

    payment.gothiaapi:
        class:           %payment.gothiaapi.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     gothiaapi
            parameters:  ~
            class:       %payment.gothiaapi.class%

    payment.paybybillapi:
        class:           %payment.paybybill.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     paybybillapi
            parameters:  ~
            class:       %payment.paybybill.class%

    payment.couponapi:
        class:           %payment.coupon.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     couponapi
            parameters:  ~
            class:       %payment.coupon.class%

    payment.pensioapi:
        class:           %payment.pensio.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     pensioapi
            parameters:  ~
            class:       %payment.pensio.class%
