parameters:
    payment.dibsapi.class: Hanzo\Bundle\PaymentBundle\Dibs\DibsApi
    payment.gothiaapi.class: Hanzo\Bundle\PaymentBundle\Gothia\GothiaApi

services:
    payment.dibsapi:
        class:           %payment.dibsapi.class%
        factory_service: service_factory
        factory_method:  get
        arguments: 
            service:     dibsapi 
            parameters:  ~ 
            class:       %payment.dibsapi.class%

    payment.gothiaapi:
        class:           %payment.gothiaapi.class%
        factory_service: service_factory
        factory_method:  get
        arguments: 
            service:     gothiaapi
            parameters:  ~ 
            class:       %payment.gothiaapi.class%
