QuickOrderBundle_homepage:
    pattern:  /quickorder/
    defaults: { _controller: QuickOrderBundle:Default:index }

quickorder_get_sku:
    pattern:    /quickorder/get-sku
    defaults:
        _controller: QuickOrderBundle:Default:getSku
        _format: json
    requirements:
        _format: html|json

quickorder_load_from_list:
    pattern: /quickorder/load-wishlist
    defaults:
        _controller: AccountBundle:Wishlist:wishListToBasket
    methods: [POST]
