QuickOrderBundle_homepage:
    pattern:  /quickorder/
    defaults: { _controller: QuickOrderBundle:Default:index }

quickorder_get_sku:
    pattern:    /quickorder/get-sku
    defaults:
        _controller: QuickOrderBundle:Default:getSku
        _format: json
    requirements:
        _format: html|json