parameters:
#    quick_order.example.class: Hanzo\Bundle\QuickOrderBundle\Example

services:
#    quick_order.example:
#        class: %quick_order.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
