admin:
    pattern:  /admin/
    defaults: { _controller: AdminBundle:Default:index }

admin_settings:
    pattern:  /admin/settings/
    defaults: { _controller: AdminBundle:Settings:index }

admin_setting_add:
    pattern:  /admin/settings/add/{domain_setting}
    defaults:
        _controller: AdminBundle:Settings:addSetting
        domain_setting: false

admin_settings_domain:
    pattern:  /admin/settings/domain/{domain_key}
    defaults:
        _controller: AdminBundle:Settings:domain
        domain_key: 'COM'

admin_settings_payment_delivery:
    pattern:  /admin/settings/paymentdelivery/{domain_key}
    defaults:
        _controller: AdminBundle:Settings:paymentdelivery
        domain_key: 'COM'

admin_settings_washing_instructions:
    pattern:  /admin/settings/washinginstructions/{code}
    defaults:
        _controller: AdminBundle:Settings:washingInstructionsIndex
        code: null
    requirements:
        code: \d+

admin_settings_washing_instructions_locale:
    pattern:  /admin/settings/washinginstructions/locale/{locale}
    defaults: { _controller: AdminBundle:Settings:washingInstructionsIndex }

admin_settings_washing_instructions_edit:
    pattern:  /admin/settings/washinginstructions/edit/{id}
    defaults:
        _controller: AdminBundle:Settings:washingInstructionsEdit
        id: null
    requirements:
        id: \d+
admin_settings_washing_instructions_delete:
    pattern:  /admin/settings/washinginstructions/delete/{id}/{locale}
    defaults:
        _controller: AdminBundle:Settings:washingInstructionsDelete
        _format: json
    requirements:
        _format: html|json
        id: \d+

admin_settings_messages_edit:
    pattern:  /admin/settings/messages/edit/{id}/{locale}
    defaults:
        _controller: AdminBundle:Settings:messagesI18nView
        locale: null
    requirements:
        id: \d+
admin_settings_messages_edit_ns:
    pattern:  /admin/settings/messages/edit-ns/{id}
    defaults:
        _controller: AdminBundle:Settings:messagesViewNs
        id: null
    requirements:
        id: \d+

admin_settings_messages:
    pattern:  /admin/settings/messages/{ns}
    defaults:
        _controller: AdminBundle:Settings:messagesIndex
        ns: null

admin_settings_messages_locale:
    pattern:  /admin/settings/messages/locale/{locale}
    defaults:
        _controller: AdminBundle:Settings:messagesIndex
admin_settings_messages_delete:
    pattern:  /admin/settings/messages/delete/{id}/{locale}
    defaults:
        _controller: AdminBundle:Settings:messagesDelete
        _format: json
    requirements:
        _format: html|json
        id: \d+


admin_cms:
    pattern:  /admin/cms/{locale}
    defaults: 
        _controller: AdminBundle:Cms:index
        locale: 'en_GB'

admin_cms_add:
    pattern:  /admin/cms/add/{locale}
    defaults:
        _controller: AdminBundle:Cms:add
        locale: 'en_GB'

admin_cms_edit:
    pattern:  /admin/cms/edit/{id}/{locale}
    defaults:
        _controller: AdminBundle:Cms:edit
        id: 0
        locale: 'en_GB'
    requirements:
        id: \d+

admin_cms_delete:
    pattern:  /admin/cms/delete/{id}
    defaults:
        _controller: AdminBundle:Cms:delete
        id: 0
    requirements:
        id: \d+

admin_cms_update_tree:
    pattern:  /admin/cms/update-tree/
    defaults:
        _controller: AdminBundle:Cms:updateCmsTree
        _format: json
    requirements:
        _format: html|json

admin_cms_redirects:
    pattern:  /admin/cms/redirects/
    defaults: { _controller: AdminBundle:Cms:redirectsIndex }

admin_cms_redirect_edit:
    pattern:  /admin/cms/redirects/edit/{id}
    defaults:
        _controller: AdminBundle:Cms:redirectEdit
        id: null
    requirements:
        id: \d+

admin_cms_redirect_delete:
    pattern:  /admin/cms/redirects/delete/{id}
    defaults:
        _controller: AdminBundle:Cms:redirectDelete
    requirements:
        id: \d+

admin_products:
    pattern:  /admin/products/cat/{category_id}/{subcategory_id}
    defaults:
        _controller: AdminBundle:Products:index
        category_id: 0
        subcategory_id: 0
    requirements:
        category_id: \d+
        subcategory_id: \d+

admin_product:
    pattern:  /admin/products/id/{id}
    defaults:
        _controller: AdminBundle:Products:view
    requirements:
        id: \d+

admin_products_sort:
    pattern:  /admin/products/sort/{category_id}/
    defaults:
        _controller: AdminBundle:Products:sort
        category_id: 0

admin_products_sort_update:
    pattern:  /admin/products/update-sort/
    defaults:
        _controller: AdminBundle:Products:updateSort
        _format: json
    requirements:
        _format: html|json

admin_product_ref_add:
    pattern:  /admin/products/add-reference/
    defaults:
        _controller: AdminBundle:Products:addReference
        _format: json
    requirements:
        _format: html|json

admin_product_ref_delete:
    pattern:  /admin/products/delete-reference/{image_id}/{product_id}
    defaults:
        _controller: AdminBundle:Products:deleteReference
        _format: json
    requirements:
        _format: html|json
        image_id: \d+
        product_id: \d+

admin_product_cat_add:
    pattern:  /admin/products/add-category/
    defaults:
        _controller: AdminBundle:Products:addCategory
        _format: json
    requirements:
        _format: html|json

admin_product_cat_delete:
    pattern:  /admin/products/delete-category/{category_id}/{product_id}
    defaults:
        _controller: AdminBundle:Products:deleteCategory
        _format: json
    requirements:
        _format: html|json
        category_id: \d+
        product_id: \d+

admin_category_edit:
    pattern:  /admin/category/{id}/{locale}
    defaults:
        _controller: AdminBundle:Category:editCategory
        id: null
        locale: null
    requirements:
        id: \d+
admin_category_add:
    pattern:  /admin/category/add/{id}/{locale}
    defaults:
        _controller: AdminBundle:Category:addCategory
        locale: null
    requirements:
        id: \d+
admin_category_delete:
    pattern:  /admin/category/delete/{id}
    defaults:
        _controller: AdminBundle:Category:deleteCategory
        _format: json
    requirements:
        _format: html|json
        id: \d+
admin_category_delete_translation:
    pattern:  /admin/category/delete-translation/{id}/{locale}
    defaults:
        _controller: AdminBundle:Category:deleteTranslation
        _format: json
    requirements:
        _format: html|json
        id: \d+

admin_customers:
    pattern:  /admin/customers/{pager}
    defaults:
        _controller: AdminBundle:Customers:index
        pager: 1

admin_customer:
    pattern:  /admin/customer/{id}
    defaults:
        _controller: AdminBundle:Customers:view
    requirements:
        id: \d+

admin_customer_address:
    pattern:  /admin/customer/address/{id}/{type}
    defaults:
        _controller: AdminBundle:Customers:editAddress
        type: null
    requirements:
        id: \d+

admin_orders:
    pattern:  /admin/orders/{pager}
    defaults:
        _controller: AdminBundle:Orders:index
        pager: 1
        id: null

admin_customer_orders:
    pattern:  /admin/customer/orders/{id}/{pager}
    defaults:
        _controller: AdminBundle:Orders:index
        pager: 1
        id: null
    requirements:
        id: \d+

admin_customer_order:
    pattern:  /admin/customer/orders/id/{order_id}
    defaults:
        _controller: AdminBundle:Orders:view
    requirements:
        order_id: \d+

admin_consultants:
    pattern:  /admin/consultants/{pager}
    defaults:
        _controller: AdminBundle:Consultants:index
        pager: 1
    requirements:
        pager: \d+
admin_consultants_events:
    pattern:  /admin/consultants/events
    defaults:
        _controller: AdminBundle:Consultants:indexEvents
        pager: 1
    requirements:
        pager: \d+

admin_consultants_export:
    pattern:  /admin/events/export
    defaults:
        _controller: AdminBundle:Consultants:export

admin_consultant:
    pattern:  /admin/consultant/{id}
    defaults:
        _controller: AdminBundle:Consultants:view
    requirements:
        id: \d+

admin_consultant_update_settings:
    pattern:  /admin/consultants/update-setting
    defaults:
        _controller: AdminBundle:Consultants:updateSetting
        _format: json
    requirements:
        _format: html|json

admin_postalcode:
    pattern:  /admin/settings/postalcode/{pager}
    defaults:
        _controller: AdminBundle:PostalCode:index
        pager: 1
        locale: null
    requirements:
        pager: \d+
admin_postalcode_locale:
    pattern:  /admin/settings/postalcode/locale/{locale}/{pager}
    defaults:
        _controller: AdminBundle:PostalCode:index
        pager: 1
        locale: null
    requirements:
        pager: \d+

admin_postalcode_edit:
    pattern:  /admin/settings/postalcode/edit/{id}
    defaults:
        _controller: AdminBundle:PostalCode:view
        id: null
    requirements:
        id: \d+
admin_postalcode_delete:
    pattern:  /admin/settings/postalcode/delete/{id}
    defaults:
        _controller: AdminBundle:PostalCode:delete
    requirements:
        id: \d+

admin_cache_jscss:
    pattern:  /admin/cache/jscss
    defaults:
        _controller: AdminBundle:Cache:clear
        jscss: true
        router: false
        redis: false
        file: false

admin_cache_router:
    pattern:  /admin/cache/router
    defaults:
        _controller: AdminBundle:Cache:clear
        js_css: false
        router: true
        redis: false
        file: false

admin_cache_redis:
    pattern:  /admin/cache/redis
    defaults:
        _controller: AdminBundle:Cache:clear
        js_css: false
        router: false
        redis: true
        file: false

admin_cache_file:
    pattern:  /admin/cache/file
    defaults:
        _controller: AdminBundle:Cache:clear
        js_css: false
        router: false
        redis: false
        file: true

admin_orders_sync_list_failed:
    pattern: /admin/orders/sync/list-failed
    defaults:
        _controller: AdminBundle:Orders:syncStatus
        status: 'failed'

admin_orders_resync_sync:
    pattern: /admin/orders/sync/{order_id}
    defaults:
        _controller: AdminBundle:Orders:resync
        order_id: 0
    requirements:
        order_id: \d+

admin_orders_preview:
    pattern: /admin/orders/preview/{order_id}
    defaults:
        _controller: AdminBundle:Orders:preview
        order_id: 0
    requirements:
        order_id: \d+

admin_orders_delete:
    pattern: /admin/orders/delete/{order_id}
    defaults:
        _controller: AdminBundle:Orders:delete
        order_id: 0
    requirements:
        order_id: \d+
