admin:
    pattern:  /admin/
    defaults: { _controller: AdminBundle:Default:index }

admin_settings:
    pattern:  /admin/settings/
    defaults: { _controller: AdminBundle:Settings:index }

admin_setting_add:
    pattern:  /admin/settings/add/{domain_setting}
    defaults: 
        _controller: AdminBundle:Settings:addSetting
        domain_setting: false

admin_settings_domain:
    pattern:  /admin/settings/domain/{domain_key}
    defaults: 
        _controller: AdminBundle:Settings:domain
        domain_key: 'COM'

admin_category:
    pattern:  /admin/category/
    defaults: { _controller: AdminBundle:Category:index }

admin_cms:
    pattern:  /admin/cms/
    defaults: { _controller: AdminBundle:Cms:index }

admin_cms_add:
    pattern:  /admin/cms/add/{locale}
    defaults: 
        _controller: AdminBundle:Cms:add
        locale: 'en_EN'

admin_cms_edit:
    pattern:  /admin/cms/edit/{id}/{locale}
    defaults: 
        _controller: AdminBundle:Cms:edit
        id: 0
        locale: 'en_EN'
    requirements:
        id: \d+

admin_cms_delete:
    pattern:  /admin/cms/delete/{id}
    defaults: 
        _controller: AdminBundle:Cms:delete
        id: 0
    requirements:
        id: \d+

admin_cms_update_tree:
    pattern:  /admin/cms/update-tree/
    defaults:
        _controller: AdminBundle:Cms:updateCmsTree
        _format: json
    requirements:
        _format: html|json

admin_products:
    pattern:  /admin/products/cat/{category_id}/{subcategory_id}
    defaults:
        _controller: AdminBundle:Products:index
        category_id: 0
        subcategory_id: 0
    requirements:
        category_id: \d+
        subcategory_id: \d+

admin_product:
    pattern:  /admin/products/id/{id}
    defaults:
        _controller: AdminBundle:Products:view
    requirements:
        id: \d+

admin_products_sort:
    pattern:  /admin/products/sort/{category_id}/
    defaults:
        _controller: AdminBundle:Products:sort
        category_id: 0

admin_products_sort_update:
    pattern:  /admin/products/update-sort/
    defaults:
        _controller: AdminBundle:Products:updateSort
        _format: json
    requirements:
        _format: html|json

admin_product_ref_add:
    pattern:  /admin/products/add-reference/
    defaults:
        _controller: AdminBundle:Products:addReference
        _format: json
    requirements:
        _format: html|json

admin_product_ref_delete:
    pattern:  /admin/products/delete-reference/{image_id}/{product_id}
    defaults:
        _controller: AdminBundle:Products:deleteReference
        _format: json
    requirements:
        _format: html|json
        image_id: \d+
        product_id: \d+

admin_product_cat_add:
    pattern:  /admin/products/add-category/
    defaults:
        _controller: AdminBundle:Products:addCategory
        _format: json
    requirements:
        _format: html|json

admin_product_cat_delete:
    pattern:  /admin/products/delete-category/{category_id}/{product_id}
    defaults:
        _controller: AdminBundle:Products:deleteCategory
        _format: json
    requirements:
        _format: html|json
        category_id: \d+
        product_id: \d+

admin_customers:
    pattern:  /admin/customers/{pager}
    defaults: 
        _controller: AdminBundle:Customers:index
        pager: 1

admin_customer:
    pattern:  /admin/customer/{id}
    defaults:
        _controller: AdminBundle:Customers:view
    requirements:
        id: \d+

admin_customer_orders:
    pattern:  /admin/customer/orders/{id}/{pager}
    defaults:
        _controller: AdminBundle:Orders:index
        pager: 1
        id: null
    requirements:
        id: \d+

admin_customer_order:
    pattern:  /admin/customer/orders/id/{order_id}
    defaults:
        _controller: AdminBundle:Orders:view
    requirements:
        order_id: \d+

admin_consultants:
    pattern:  /admin/consultants/{pager}
    defaults: 
        _controller: AdminBundle:Consultants:index
        pager: 1

admin_consultant:
    pattern:  /admin/consultant/{id}
    defaults:
        _controller: AdminBundle:Consultants:view
    requirements:
        id: \d+

admin_cache:
    pattern:  /admin/cache/
    defaults: { _controller: AdminBundle:Cache:index }

admin_cache_jscss:
    pattern:  /admin/cache/
    defaults: { _controller: AdminBundle:Cache:index }

admin_cache_redis:
    pattern:  /admin/cache/
    defaults: { _controller: AdminBundle:Cache:index }

admin_cache_productpicture:
    pattern:  /admin/cache/
    defaults: { _controller: AdminBundle:Cache:index }
