parameters:
    hanzo_admin.cms_link.twig.extension.class: Hanzo\Bundle\AdminBundle\Twig\Extension\AdminExtension

services:
    cms.node.deleted.listener:
        class: Hanzo\Bundle\ServiceBundle\Services\CacheService
        arguments:
            - [@pdl.phpredis.main]
            - []
        tags:
            - { name: kernel.event_listener, event: cms.node.deleted, method: clearRedisCache }
            - { name: kernel.event_listener, event: cms.node.updated, method: clearRedisCache }
            - { name: kernel.event_listener, event: cms.node.moved, method: clearRedisCache }
            - { name: kernel.event_listener, event: category.node.deleted, method: clearRedisCache }
            - { name: kernel.event_listener, event: category.product_sort.update, method: clearRedisCache }

    muneris.guzzle_postal_client:
        class: %guzzle.client.class%
        arguments:
            - %muneris.host%
        tags:
            - { name: guzzle.client }

    hanzo_admin.cms_link.twig.extension:
        class: %hanzo_admin.cms_link.twig.extension.class%
        arguments:
            - %locale%
            - @router.default
        tags:
            -   { name: twig.extension }
