parameters:
#    admin.example.class: Hanzo\Bundle\AdminBundle\Example

services:
    cms.node.deleted.listener:
        class: Hanzo\Bundle\ServiceBundle\Services\CacheService
        arguments:
            - [@snc_redis.default_client]
            - []
        tags:
            - { name: kernel.event_listener, event: cms.node.deleted, method: clearRedisCache }
