parameters:
#    events.example.class: Hanzo\Bundle\EventsBundle\Example

services:
    hanzo.event.checkout.listener:
        class: Hanzo\Bundle\EventsBundle\Event\CheckoutListener
        arguments: [ @mail_manager, @ax_manager, @translator ]
        tags:
            - { name: kernel.event_listener, event: order.summery.finalize, method: onFinalize, prioriy: 10 }
