Hanzo\Model\Events:
    properties:
        host:
            - NotBlank:
                message: events.host.required.error
            - MinLength: 2
        address_line_1:
            - NotBlank:
                message: events.address_line_1.required.error
            - MinLength: 2
        postal_code:
            - NotBlank:
                message: events.postal_code.required.error
            - MinLength: 2
        city:
            - NotBlank:
                message: events.city.required.error
            - MinLength: 2
        phone:
            - NotBlank:
                message: events.phone.required.error
            - MinLength: 6
        email:
            - NotBlank:
                message: events.email.required.error
            - Email:
                message: events.email.required.error
