Hanzo\Model\Events:
    properties:
        host:
            - NotBlank:
                message: host.required
            - Length:
                min: 2
                minMessage: host.required
        event_date:
            - NotBlank:
                message: event_date.required
        address_line_1:
            - NotBlank:
                message: address_line_1.required
            - Length:
                min: 2
                minMessage: address_line_1.required
        postal_code:
            - NotBlank:
                message: postal_code.required
            - Length:
                min: 2
                minMessage: postal_code.required
        city:
            - NotBlank:
                message: city.required
            - Length:
                min: 2
                minMessage: city.required
        phone:
            - NotBlank:
                message: phone.required
            - Length:
                min: 8
                minMessage: phone.min.length
            - Regex:
                pattern: "/^\d+$/"
                match:   true
                message: phone.not.valid
        email:
            - NotBlank:
                message: email.required
            - Email:
                message: email.required
