Hanzo\Model\Events:
    properties:
        host:
            - NotBlank:
                message: host.required
            - MinLength: 2
        address_line_1:
            - NotBlank:
                message: address_line_1.required
            - MinLength: 2
        postal_code:
            - NotBlank:
                message: postal_code.required
            - MinLength: 2
        city:
            - NotBlank:
                message: city.required
            - MinLength: 2
        phone:
            - NotBlank:
                message: phone.required
            - MinLength:
                limit: 8
                message: phone.min.length
            - Regex:
                pattern: "/^\d+$/"
                match:   true
                message: phone.not.valid
        email:
            - NotBlank:
                message: email.required
            - Email:
                message: email.required
