language: php

php:
  - 5.5

services:
  - redis-server

before_script:
  - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cp app/config/parameters.ini.dist app/config/parameters.ini
  - composer self-update
  - sudo service mysql stop
  - composer install
  - sudo service mysql start

script: phpunit -c app/
