language: php

php:
  - 5.5

services:
  - redis-server

before_install:
  - sudo apt-get update
  - sudo apt-get --reinstall install -qq language-pack-da language-pack-de language-pack-en language-pack-fi language-pack-nb language-pack-nl language-pack-se

before_script:
  - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'date.timezone = "Europe/Copenhagen"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cp app/config/parameters.ini.dist app/config/parameters.ini
  - composer self-update
  - composer install

script:
  - phpunit -c app/
  - php app/console hanzo:run-checks

notifications:
#  email:
#    recipients:
#      - pdl@bellcom.dk
#      - hd@pompdelux.dk
#      - lv@pompdelux.dk
#    on_success: always
#    on_failure: always
  webhooks:
    urls:
      - http://tools.pompdelux.com/travis-hook.php
    on_start: true
