language: php

php:
  - 5.5

services:
  - redis-server

before_script:
  - echo "redis = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cp app/config/parameters.ini.dist app/config/parameters.ini
  - composer self-update
  - composer install

script: phpunit -c app/
