login:
    path: /login
    defaults:
        _controller: AccountBundle:Security:login

logout:
    path: /logout
    defaults:
        _controller: AccountBundle:Security:logout

login_check:
    path: /login_check

_account:
    path: /account
    defaults:
        _controller: AccountBundle:Default:index

_account_create:
    path: /account/create
    defaults:
        _controller: AccountBundle:Default:create

_account_lost_password:
    path: /account/password-forgotten
    defaults:
        _controller: AccountBundle:Default:passwordForgotten

_account_history:
    path: /account/history/{pager}
    defaults:
        _controller: AccountBundle:History:index
        pager: 1

_account_show_order:
    path: /account/order/{order_id}/show
    defaults:
        _controller: AccountBundle:History:view
    requirements:
        order_id: \d+

_account_edit_order:
    path: /account/order/{order_id}/edit
    defaults:
        _controller: AccountBundle:History:edit
    requirements:
        order_id: \d+

_account_stop_edit_order:
    path: /account/order/{order_id}/stop-edit
    defaults:
        _controller: AccountBundle:Default:stopOrderEdit
    requirements:
        order_id: \d+

_account_delete_order:
    path: /account/order/{order_id}/delete
    defaults:
        _controller: AccountBundle:History:delete
    requirements:
        order_id: \d+

_account_edit:
    path: /account/edit
    defaults:
        _controller: AccountBundle:Default:edit

_account_edit_address:
    path: /account/edit/address/{type}/{shipping_id}
    defaults:
        _controller: AccountBundle:Default:editAddress
        type: ''
        shipping_id: ''

_account_check:
    path: /account/check/{type}
    defaults:
        _controller: AccountBundle:Default:check

# ----------------
# wishlist section
# ----------------
_account_wishlist_create:
    path: /account/wishlist/create
    defaults:
        _controller: AccountBundle:Wishlist:add

_account_wishlist_remove:
    path: /account/wishlist/remove/{id}
    defaults:
        _controller: AccountBundle:Wishlist:delete
    requirements:
        order_id: ^[A-Z0-9]{5}$

_account_wishlist_add_item:
    path: /account/wishlist/add-item
    defaults:
        _controller: AccountBundle:Wishlist:addItem
    methods: [POST]

_account_wishlist_remove_item:
    path: /account/wishlist/remove-item/{product_id}
    defaults:
        _controller: AccountBundle:Wishlist:deleteItem
    methods: [POST]
    requirements:
        product_id: \d+

_account_wishlist_update_item:
    path: /account/wishlist/update-item
    defaults:
        _controller: AccountBundle:Wishlist:updateItem
    methods: [POST]

_account_wishlist_remove_all:
    path: /account/wishlist/delete-all-items
    defaults:
        _controller: AccountBundle:Wishlist:removeAllItems

_account_wishlist_load:
    path: /account/wishlist/load/{listId}
    defaults:
        _controller: AccountBundle:Wishlist:wishListToBasket
        listId: null

# ----------------
