login:
    pattern: /login
    defaults:
        _controller: AccountBundle:Security:login

logout:
    pattern: /logout
    defaults:
        _controller: AccountBundle:Security:logout

login_check:
    pattern:   /login_check

_account:
    pattern: /account
    defaults:
        _controller: AccountBundle:Default:index
_account_create:
    pattern: /account/create
    defaults:
        _controller: AccountBundle:Default:create
_account_lost_password:
    pattern: /account/password-forgotten
    defaults:
        _controller: AccountBundle:Default:passwordForgotten

_account_nno:
    pattern: /account/nno/{phone}
    defaults:
        _controller: AccountBundle:NNO:check
        phone: ''

_account_history:
    pattern: /account/history
    defaults:
        _controller: AccountBundle:History:index

_account_show_order:
    pattern: /account/history/{order_id}
    defaults:
        _controller: AccountBundle:History:view
    requirements:
        order_id: \d+

_account_edit:
    pattern: /account/edit
    defaults:
        _controller: AccountBundle:Default:edit
