parameters:
    account_user_provider.class: Hanzo\Bundle\AccountBundle\Security\User\UserProvider

#    account.example.class: Hanzo\Bundle\AccountBundle\Example

services:
    hanzo.account.security.provider:
        class: %account_user_provider.class%

#    account.example:
#        class: %account.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
