services:
    security.access.domain_restriction:
        class:      Hanzo\Bundle\AccountBundle\Security\Authorization\Voter\DomainVoter
        arguments:  [@service_container]
        public:     false
        tags:
            -       { name: security.voter }

    hanzo.address_formatter:
        class:     Hanzo\Bundle\AccountBundle\AddressFormatter
        arguments: ['%locale%', @templating, @translator]


    hanzo.logout_success_handler:
        class:  Hanzo\Bundle\AccountBundle\Handler\LogoutSuccessHandler
        arguments:  [@service_container, @router]
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    hanzo.send_wishlist_handler:
        class: Hanzo\Bundle\AccountBundle\Handler\SendWishlistMailHandler
        arguments:
          mailService: @mail_manager
          router: @router
