parameters:
    account_user_provider.class: Hanzo\Bundle\AccountBundle\Security\User\UserProvider

services:
    hanzo.account.security.provider:
        class: %account_user_provider.class%

    security.access.domain_restriction:
        class:      Hanzo\Bundle\AccountBundle\Security\Authorization\Voter\DomainVoter
        arguments:  [@service_container]
        public:     false
        tags:
            -       { name: security.voter }

    hanzo.logout_success_handler:
        class:  Hanzo\Bundle\AccountBundle\Handler\LogoutSuccessHandler
        arguments:  [@service_container, @router]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
