Hanzo\Model\Addresses:
    properties:
        first_name:
            - NotBlank:
                message: address.first_name.required
                groups: [shipping, company_shipping, payment, overnightbox]
            - Length:
                min: 2
                minMessage: address.first_name.required
        last_name:
            - NotBlank:
                message: address.last_name.required
                groups: [shipping, company_shipping, payment, overnightbox]
            - Length:
                min: 2
                minMessage: address.last_name.required
        address_line_1:
            - NotBlank:
                message: address.address_line_1.required
                groups: [shipping, company_shipping, payment, overnightbox, customer]
            - Length:
                min: 2
                max: 35
                minMessage: address.address_line_1.required
                maxMessage: address.address_line_1.required
        postal_code:
            - NotBlank:
                message: address.postal_code.required
                groups: [shipping, company_shipping, payment, overnightbox, customer]
            - Length:
                min: 2
                minMessage: address.postal_code.required
        city:
            - NotBlank:
                message: address.city.required
                groups: [shipping, company_shipping, payment, overnightbox, customer]
            - Length:
                min: 2
                minMessage: address.city.required
        countries_id:
            - NotBlank:
                message: address.countries_id.required
                groups: [shipping, company_shipping, payment, overnightbox, customer]
            - Type:
                type: integer
        company_name:
            - NotBlank:
                message: address.company_name.required
                groups: [company_shipping]
    constraints:
        - Callback:
            methods: [isFullNameWithinLimits]
            groups:
                - shipping
                - company_shipping
                - payment
                - overnightbox
                - customer
                - customer_edit

Hanzo\Model\Customers:
    properties:
        first_name:
            - NotBlank:
                message: address.first_name.required
                groups: [customer, customer_edit]
            - Length:
                min: 2
                minMessage: address.first_name.min.length
                groups: [customer, customer_edit]
        last_name:
            - NotBlank:
                message: address.last_name.required
                groups: [customer, customer_edit]
            - Length:
                min: 2
                minMessage: address.last_name.min.length
                groups: [customer, customer_edit]
        phone:
            - NotBlank:
                message: phone.required
                groups: [customer, customer_edit]
            - Length:
                min: 8
                max: 12
                exactMessage: phone.min.length
                groups: [customer, customer_edit]
            - Regex:
                pattern: "/^\d+$/"
                match:   true
                message: phone.not.valid
                groups: [customer, customer_edit]
        email:
            - NotBlank:
                message: email.required
                groups: [customer, customer_edit]
            - Email:
                message: email.not.valid
                groups: [customer, customer_edit]
        password:
            - NotBlank:
                message: password.required
                groups: [customer]
            - Length:
                min: 5
                minMessage: password.min.length
                groups: [customer]
    # NICETO: figure out why this does not trigger an error
    getters:
        emailUniq:
            - "True":
                message: email.exists
                groups:  [customer]
    constraints:
        - Callback:
            methods: [isFullNameWithinLimits]
            groups:
                - customer
                - customer_edit

