CategoryBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: CategoryBundle:Default:index }

named_list:
    pattern:  /products/list/{type}/{filter}
    defaults:
        _controller: CategoryBundle:Default:listProducts
        type: context
        filter: G_

list_category_products:
    pattern: /category/listProducts/{cms_id}/{show}/{pager}
    defaults:
        _controller: CategoryBundle:Default:listCategoryProducts
        pager: 1
