parameters:
#    hanzo_category.example.class: Hanzo\Bundle\CategoryBundle\Example

services:
#    hanzo_category.example:
#        class: %hanzo_category.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
