WebServicesBundle_homepage:
    pattern:  /wolla/{name}
    defaults: { _controller: WebServicesBundle:Default:index }

WebServicesBundle_soap:
    pattern:  /soap/{version}/{service_name}
    defaults: { _controller: WebServicesBundle:Soap:index, version: v1 }
    requirements:
      service_name: "[a-zA-Z0-9_]+"

WebServicesBundle_rest:
    pattern:  /rest/{version}/{service_name}
    defaults: { _controller: WebServicesBundle:Rest:index, version: v1 }
    requirements:
      service_name: "[a-zA-Z0-9_]+"
      version: "v[0-9]+"
      _method:  GET|POST
      _format: JSON

#http://www.pompdelux.com/video.php?src=Berte_LS_LONG_TSHIRT&height=360&width=248

