ws_index:
    pattern:  /wolla/{name}
    defaults: { _controller: WebServicesBundle:Default:index }

ws_cookie:
    pattern:  /m.test
    defaults: { _controller: WebServicesBundle:Default:cookie }

ws_product_video:
    pattern:  /rest/{version}/video
    defaults:
        _controller: WebServicesBundle:RestVideo:get
        version: v1

ws_soap_test:
    pattern:  /soaptest/
    defaults: { _controller: WebServicesBundle:Soap:test }

ws_jaiks_callback:
    pattern: /rest/{version}/jaiks
    defaults:
        _controller: WebServicesBundle:Rest:jaiks
        version: v1
