ws_index:
    pattern:  /wolla/{name}
    defaults: { _controller: WebServicesBundle:Default:index }

ws_cookie:
    pattern:  /m.test
    defaults: { _controller: WebServicesBundle:Default:cookie }

ws_soap:
    pattern:  /soap/{version}/{service_name}/
    defaults: { _controller: WebServicesBundle:Soap:index, version: v1 }
    requirements:
        service_name: "[a-zA-Z0-9_]+"

# /rest/v1/stock-check/{10}?master=foo&color=bar&size=baz
ws_stock:
    pattern:    /rest/{version}/stock-check/{id}
    defaults:
        _controller: WebServicesBundle:RestStock:check
        version: v1
        id: 0
    requirements:
        _method:  GET
        id: \d+
        version: "v[0-9]+"

ws_product_video:
    pattern:  /rest/{version}/video
    defaults:
        _controller: WebServicesBundle:RestVideo:get
        version: v1

ws_google_maps_proxy:
    pattern: /rest/{version}/gm/proxy/{query}/{country}
    defaults:
        _controller: WebServicesBundle:RestGoogle:proxy
        version: v1
        query: ''
        country: ''

ws_google_maps_near_you:
    pattern: /rest/{version}/gm/near_you/{type}/{latitude}/{longitude}
    defaults:
        _controller: WebServicesBundle:RestGoogle:nearYou
        version: v1
        type: 'near'
        latitude: 0.00
        longitude: 0.00
    requirements:
        type: '(near|hus)'

ws_google_maps_consultants_map:
    pattern: /rest/{version}/gm/consultants
    defaults:
        _controller: WebServicesBundle:RestGoogle:consultants

ws_soap_test:
    pattern:  /soaptest/
    defaults: { _controller: WebServicesBundle:Soap:test }

ws_jaiks_callback:
    pattern: /rest/{version}/jaiks
    defaults:
        _controller: WebServicesBundle:Rest:jaiks
        version: v1
