ws_index:
    pattern:  /wolla/{name}
    defaults: { _controller: WebServicesBundle:Default:index }

ws_cookie:
    pattern:  /m.test
    defaults: { _controller: WebServicesBundle:Default:cookie }

ws_product_video:
    pattern:  /rest/{version}/video
    defaults:
        _controller: WebServicesBundle:RestVideo:get
        version: v1

ws_google_maps_near_you:
    pattern: /rest/{version}/gm/near_you/{type}/{latitude}/{longitude}/{showAll}
    defaults:
        _controller: WebServicesBundle:RestGoogle:nearYou
        version: v1
        type: 'near'
        latitude: 0.00
        longitude: 0.00
        showAll: 0
    requirements:
        type: '(near|hus)'

ws_google_maps_consultants_map:
    pattern: /rest/{version}/gm/consultants
    defaults:
        _controller: WebServicesBundle:RestGoogle:consultants

ws_soap_test:
    pattern:  /soaptest/
    defaults: { _controller: WebServicesBundle:Soap:test }

ws_jaiks_callback:
    pattern: /rest/{version}/jaiks
    defaults:
        _controller: WebServicesBundle:Rest:jaiks
        version: v1
