parameters:
    google.twig_extension.class: Hanzo\Bundle\GoogleBundle\Twig\Extension\GoogleExtension

services:
    google.twig_extension:
        class: %google.twig_extension.class%
        tags:
            - { name: twig.extension }
        arguments: [%google.analytics_code%, %google.conversion_id%, %google.site_verification%, %google.google_tag_manager_id%]
