parameters:
    muneris.service.maxmind.class: Hanzo\Bundle\MunerisBundle\Services\MaxMind;

services:
    muneris.guzzle.client:
        class: "%guzzle.client.class%"
        arguments:
            -  "%muneris.host%"
        tags:
            -  { name: guzzle.client }

    muneris.maxmind:
        class: Hanzo\Bundle\MunerisBundle\Services\MaxMind
        arguments:
            - @service_container
            - @muneris.guzzle.client
            - @redis.permanent
            - @logger
