imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type:                     fingers_crossed
            action_level:             error
            handler:                  nested
        nested:
            type:                     stream
            path:                     %kernel.logs_dir%/%kernel.environment%.log
            level:                    debug

framework:
    session:
        default_locale: nb_NO
        path: '/app_test.php/nb_NO'
    templating:
        assets_base_urls:
            http:                     [ %cdn% ]

propel:
    dbal:
        default_connection:           default
        connections:
            default:
                driver:               %database_driver%
                user:                 %test_no_database_user%
                password:             %test_no_database_password%
                dsn:                  mysql:host=%test_no_database_host%;dbname=%test_no_database_name%
                options:              {}
                attributes:           {}
