imports:
  - resource: parameters.ini
  - resource: parameters.php
framework:
  translator: null
  secret: '%secret%'
  charset: UTF-8
  router:
    resource: '%kernel.root_dir%/config/routing.yml'
  form: true
  csrf_protection: true
  validation:
    enabled: true
    enable_annotations: true
  templating:
    engines: [twig]
    assets_version: '%assets_version%'
  session:
    default_locale: '%locale%'
    auto_start: false
services:
  stock:
    class: Hanzo\Core\Stock
  hanzo.misc.twig.extension:
    class: Hanzo\Twig\Extension\MiscExtension
    arguments: ['@twig_string']
    tags: [{ name: twig.extension }]
  hanzo.asset.twig.extension:
    class: Hanzo\Twig\Extension\AssetExtension
    tags: [{ name: twig.extension }]
  hanzo.maps.twig.extension:
    class: Hanzo\Twig\Extension\MapsExtension
    arguments: ['@twig_string']
    tags: [{ name: twig.extension }]
  hanzo.boot:
    class: Hanzo\Core\HanzoBoot
    arguments: ['@router']
    tags: [{ name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: -10 }]
twig:
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  form:
    resources: ['SimpleThingsFormExtraBundle:Form:translation_domain.html.twig']
assetic:
  debug: '%kernel.debug%'
  use_controller: false
  java: /usr/bin/java
  filters:
    cssrewrite: null
    yui_css: { jar: '%kernel.root_dir%/../bin/YUICompressor/yuicompressor-2.4.7/build/yuicompressor-2.4.7.jar' }
    yui_js: { jar: '%kernel.root_dir%/../bin/YUICompressor/yuicompressor-2.4.7/build/yuicompressor-2.4.7.jar' }
swiftmailer:
  transport: '%mailer_transport%'
  host: '%mailer_host%'
  username: '%mailer_user%'
  password: '%mailer_password%'
jms_security_extra:
  secure_controllers: true
  secure_all_services: false
propel:
  dbal:
    driver: '%database_driver%'
    options: {  }
    attributes: {  }
  path: '%kernel.root_dir%/../vendor/propel'
  phing_path: '%kernel.root_dir%/../vendor/phing'
  logging: '%kernel.debug%'
  build_properties:
    propel.project: '%database_name%'
    propel.addValidators: all
    propel.namespace.autoPackage: true
snc_redis:
  clients:
    default: { type: predis, alias: default, dsn: 'redis://%redis_cache1_host%:%redis_cache1_port%/%redis_cache1_database%' }
    session: { type: predis, alias: session, dsn: 'redis://%redis_session_host%:%redis_session_port%/%redis_session_database%' }
  session:
    client: session
    prefix: hanzo.session
simple_things_form_extra:
  translation_domain_forward_compat: true
