imports:
    - { resource: parameters.ini }
# note security is handled in config_ws_webshop.yml and config_ws_consultant.yml
#    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      ~
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    session:
        default_locale: %locale%
        auto_start:     false

services:
    stock:
        class: Hanzo\Core\Stock

    # twig extensions
    hanzo.misc.twig.extension:
        class:  Hanzo\Twig\Extension\MiscExtension
        arguments: [ @twig_string ]
        tags:
            -  { name: twig.extension }
    hanzo.asset.twig.extension:
        class:  Hanzo\Twig\Extension\AssetExtension
        tags:
            -  { name: twig.extension }
    hanzo.maps.twig.extension:
        class:  Hanzo\Twig\Extension\MapsExtension
        arguments: [ @twig_string ]
        tags:
            -  { name: twig.extension }

    hanzo.boot:
        class: Hanzo\Core\HanzoBoot
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }


# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - SimpleThingsFormExtraBundle:Form:translation_domain.html.twig

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        yui_css:
             jar: %kernel.root_dir%/../bin/YUICompressor/yuicompressor-2.4.7/build/yuicompressor-2.4.7.jar
        yui_js:
             jar: %kernel.root_dir%/../bin/YUICompressor/yuicompressor-2.4.7/build/yuicompressor-2.4.7.jar

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

# Propel Configuration
propel:
    dbal:
        driver:               %database_driver%
        user:                 %database_user%
        password:             %database_password%
        dsn:                  mysql:host=%database_host%;dbname=%database_name%
        options:              {}
        attributes:           {}
    path:       "%kernel.root_dir%/../vendor/propel"
    phing_path: "%kernel.root_dir%/../vendor/phing"
    logging:    %kernel.debug%
    build_properties:
        propel.project: %database_name%
        propel.addValidators: all
        propel.namespace.autoPackage: true


# redis configuration
snc_redis:
    connections:
        default:
            alias:    default
            host:     %redis_cache1_host%
            port:     %redis_cache1_port%
            database: %redis_cache1_database%
            logging:  %kernel.debug%
        session:
            alias:    session
            host:     %redis_session_host%
            port:     %redis_session_port%
            database: %redis_session_database%
    clients:
        default:
            alias:      default
            connection: default
        session:
            alias:      session
            connection: session
    session:
        client: session
        prefix: hanzo.session

# form addons
simple_things_form_extra:
    translation_domain_forward_compat: true
