imports:
    - resource: parameters.ini
    - resource: parameters.php

framework:
    translator: null
    secret: '%secret%'
    charset: UTF-8
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
    form: true
    csrf_protection: true
    validation:
        enabled: true
        enable_annotations: true
    templating:
        engines: [twig]
        assets_version: '%assets_version%'
    session:
        # default_locale: '%locale%'
        auto_start: false
        path: '/%locale%'

services:
    stock:
        class: Hanzo\Core\Stock

    hanzo.cache:
        class: Hanzo\Core\RedisCache
        arguments: [ '@snc_redis.default_client', '%kernel.environment%' ]
    hanzo.misc.twig.extension:
        class: Hanzo\Twig\Extension\MiscExtension
        arguments: ['@twig_string']
        tags:
            -   { name: twig.extension }
    hanzo.asset.twig.extension:
        class: Hanzo\Twig\Extension\AssetExtension
        tags:
            -   { name: twig.extension }
    hanzo.maps.twig.extension:
        class: Hanzo\Twig\Extension\MapsExtension
        arguments: ['@twig_string']
        tags:
            -   { name: twig.extension }

    hanzo.routing_loader:
        class: Hanzo\Bundle\CMSBundle\CMSRouterLoader
        arguments: ['@session', '%kernel.cache_dir%']
        tags:
            -   { name: routing.loader }

    hanzo.boot_listener:
        class: Hanzo\Core\HanzoBoot
        arguments: ['@router', '@kernel']
        tags:
            -   { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: -10 }
    hanzo.exception_listener:
        class: Hanzo\Core\ExceptionHandler
        arguments: [@service_container]
        tags:
            -   { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    hanzo.login_listener:
        class: Hanzo\Bundle\AccountBundle\Event\LoginListener
        arguments: [@security.context]
        tags:
            -   { name: kernel.event_listener, event: security.interactive_login }

twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form:
        resources: ['SimpleThingsFormExtraBundle:Form:translation_domain.html.twig']

assetic:
    debug: '%kernel.debug%'
    use_controller: false
    java: /usr/bin/java
    filters:
        cssrewrite: null
        yui_css:
            jar: '%kernel.root_dir%/../bin/YUICompressor/yuicompressor-2.4.7/build/yuicompressor-2.4.7.jar'
        yui_js:
            jar: '%kernel.root_dir%/../bin/YUICompressor/yuicompressor-2.4.7/build/yuicompressor-2.4.7.jar'

swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'

propel:
    dbal:
        driver: '%database_driver%'
        options: {  }
        attributes: {  }
    path: '%kernel.root_dir%/../vendor/propel'
    phing_path: '%kernel.root_dir%/../vendor/phing'
    logging: '%kernel.debug%'

jms_security_extra:
    secure_controllers: true
    secure_all_services: false

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: 'redis://%redis_cache1_host%:%redis_cache1_port%/%redis_cache1_database%'
            options:
                connection_persistent: true
                connection_timeout: 30
                read_write_timeout: 0
        session:
            type: predis
            alias: session
            dsn: 'redis://%redis_session_host%:%redis_session_port%/%redis_session_database%'
            options:
                connection_persistent: true
                connection_timeout: 30
                read_write_timeout: 0
    session:
        client: session
        prefix: hanzo.session

simple_things_form_extra:
    translation_domain_forward_compat: true

# settings for the cms bundle.
cms:
    frontpage: 556
    twig:
        left_menu:
            type: main
            from: 20
        sub_menu:
            type: sub
            from: 400
            offset: 482

# @see https://github.com/ekino/EkinoNewRelicBundle
ekino_new_relic:
    application_name: Hanzo
    api_key: ~

# @see https://github.com/liip/LiipThemeBundle
liip_theme:
    themes: ['2012s2', '2013s1']
    active_theme: '2012s2'
    path_patterns:
        app_resource:
            - %%app_path%%/themes/%%current_theme%%/%%template%%
            - %%app_path%%/themes/fallback_theme/%%template%%
            - %%app_path%%/views/%%template%%
        bundle_resource:
            - %%bundle_path%%/Resources/themes/%%current_theme%%/%%template%%
            - %%bundle_path%%/Resources/themes/fallback_theme/%%template%%
        bundle_resource_dir:
            - %%dir%%/themes/%%current_theme%%/%%bundle_name%%/%%template%%
            - %%dir%%/themes/fallback_theme/%%bundle_name%%/%%template%%
            - %%dir%%/%%bundle_name%%/%%override_path%%
