imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

framework:
    session:
        default_locale: da_DK
        path: '/da_DK'
    templating:
        assets_base_urls:
            http: [ %cdn% ]

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:               %database_driver%
                user:                 %prod_dk_database_user%
                password:             %prod_dk_database_password%
                dsn:                  mysql:host=%prod_dk_database_host%;dbname=%prod_dk_database_name%
                options:              {}
                attributes:           {}
                slaves:
                    pdldbdk2:
                        user:         %prod_dk_database_slave_1_user%
                        password:     %prod_dk_database_slave_1_password%
                        dsn:          %prod_dk_database_slave_1_dsn%
                    pdldbdk3:
                        user:         %prod_dk_database_slave_2_user%
                        password:     %prod_dk_database_slave_2_password%
                        dsn:          %prod_dk_database_slave_2_dsn%
                    pdldbdk4:
                        user:         %prod_dk_database_slave_3_user%
                        password:     %prod_dk_database_slave_3_password%
                        dsn:          %prod_dk_database_slave_3_dsn%
            pdldbse1:
                driver:               %database_driver%
                user:                 %prod_se_database_user%
                password:             %prod_se_database_password%
                dsn:                  mysql:host=%prod_se_database_host%;dbname=%prod_se_database_name%
                options:              {}
                attributes:           {}
            pdldbno1:
                driver:               %database_driver%
                user:                 %prod_no_database_user%
                password:             %prod_no_database_password%
                dsn:                  mysql:host=%prod_no_database_host%;dbname=%prod_no_database_name%
                options:              {}
                attributes:           {}
