framework:
    translator: null
    form:       true
    secret:     '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
    csrf_protection: true
    validation:
        enabled:            true
        enable_annotations: true
    templating:
        engines:        [twig]
        assets_version: '%assets_version%'
    session:
        storage_id:     session.storage.native
        handler_id:     session.handler.redis
        gc_maxlifetime: 7200
        #  7200 = 2 hours
        # 10800 = 3 hours
    esi:
        enabled: true
    fragments:
        path: /_fragment
    trusted_hosts:   ~
    trusted_proxies: ~
    http_method_override: true

services:
    # native redis session handeling
    # https://github.com/drak/NativeSession
    session.handler.redis:
        class:     Drak\NativeSession\NativeRedisSessionHandler
        arguments: [ 'tcp://%redis_session_host%:%redis_session_port%?prefix=hanzo.session:&database=%redis_session_database%' ]

    hanzo.misc.twig.extension:
        class:     Hanzo\Twig\Extension\MiscExtension
        arguments: ['@twig_string', '@liip_theme.active_theme']
        tags:
            -   { name: twig.extension }
    hanzo.asset.twig.extension:
        class: Hanzo\Twig\Extension\AssetExtension
        tags:
            -   { name: twig.extension }
    hanzo.maps.twig.extension:
        class:     Hanzo\Twig\Extension\MapsExtension
        arguments: ['@twig_string', '@muneris.maxmind']
        tags:
            -   { name: twig.extension }

    hanzo.routing_loader:
        class:     Hanzo\Bundle\CMSBundle\CMSRouterLoader
        arguments: ['%locale%', '%kernel.cache_dir%']
        tags:
            -   { name: routing.loader }

    hanzo.boot_listener:
        class:     Hanzo\Core\HanzoBoot
        arguments: ['@security.context', '@router', '@kernel']
        tags:
            -   { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: -10 }
    hanzo.exception_listener:
        class:     Hanzo\Core\ExceptionHandler
        arguments:
            - @service_container
            - @http_kernel
        tags:
            -   { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    hanzo.login_listener:
        class:     Hanzo\Bundle\AccountBundle\Event\LoginListener
        arguments: [@security.context]
        tags:
            -   { name: kernel.event_listener, event: security.interactive_login }
    hanzo.propel_replicator:
        class:     Hanzo\Core\PropelReplicator
        arguments: [@propel.configuration]

    hanzo.external_service.logger:
        class: Hanzo\Core\ServiceLogger
        arguments: ["@logger"]
        tags:
            - { name: monolog.logger, channel: 3ps }

twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form:
        resources:
            - 'TwigBundle:Form:fields.html.twig'

swiftmailer:
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'

propel:
    dbal:
        driver:     '%database_driver%'
        options:    {}
        attributes: {}
        classname:  Glorpen\Propel\PropelBundle\Connection\EventPropelPDO
    path:             '%kernel.root_dir%/../vendor/propel'
    phing_path:       '%kernel.root_dir%/../vendor/phing'
    logging:          '%kernel.debug%'
    build_properties:
        propel.project:                   '%database_name%'
        propel.addValidators:             all
        propel.namespace.autoPackage:     true
        propel.useDateTimeClass:          false
        propel.defaultTimeStampFormat:    "Y-m-d H:i:s"
        propel.defaultTimeFormat:         "H:i:s"
        propel.defaultDateFormat:         "Y-m-d"
        propel.behavior.geocodable.class: "%kernel.root_dir%.propel.propel-behaviors.GeocodableBehavior.src.GeocodableBehavior"
        propel.behavior.event.class:      'vendor.glorpen.propel-bundle.Glorpen.Propel.PropelBundle.Behaviors.EventBehavior'
        propel.behavior.default:          "event"


jms_security_extra:
    secure_all_services: false
    expressions:         true

# settings for the cms bundle.
cms:
    frontpage: 556
    twig:
        left_menu:
            type:   main
            from:   20
        sub_menu:
            type:   sub
            from:   400
            offset: 482
        footer1_menu:
            type:   footer1
            thread: 30
        footer2_menu:
            type:   footer2
            thread: 31
        footer3_menu:
            type:   footer3
            thread: 32

# native redis caching
redis:
    class:
        # the "main" cache is for tmp caching
        main:
            host:     %redis_cache1_host%
            port:     %redis_cache1_port%
            prefix:   hanzo
            database: %redis_cache1_database%
            auth:     %redis_cache1_password%
        # permanent should be used for fast access to stuff that does not change
        # this db should never be flushed !
        permanent:
            host:     %redis_cache1_host%
            port:     %redis_cache1_port%
            prefix:   hanzo
            skip_env: true
            database: 2
            auth:     %redis_cache1_password%
        # "stock" is like "permanent" a cache that should never be flushed.
        # if it is flushed a full stock sync from AX must be performed.
        stock:
            host:     %redis_cache1_host%
            port:     %redis_cache1_port%
            prefix:   hanzo
            skip_env: true
            database: 5
            auth:     %redis_cache1_password%

# this controles wich warehouse the different countries handles stock maintainance.
stock:
    warehouses:
        main:
            - da_DK
            - de_AT
            - de_CH
            - de_DE
            - fi_FI
            - nl_NL
            - sv_SE
            - en_GB
        norway:
            - nb_NO

google:
    conversion_id:     ~
    site_verification: ~
    analytics_code:    ~

# @see https://github.com/ekino/EkinoNewRelicBundle
ekino_new_relic:
    application_name: Pompdelux
    api_key:          3909fb3d64adf610708e4fc0aa59fc956a94d03a

# @see https://github.com/liip/LiipThemeBundle
liip_theme:
    load_controllers: false
    themes:           ['2013s1', '2013s1_mobile']
    active_theme:     '2013s1'
    path_patterns:
        app_resource:
            - %%app_path%%/themes/%%current_theme%%/%%template%%
            - %%app_path%%/themes/2013s1/%%template%%
            - %%app_path%%/views/%%template%%
        bundle_resource:
            - %%bundle_path%%/Resources/themes/%%current_theme%%/%%template%%
            - %%bundle_path%%/Resources/themes/2013s1/%%template%%
        bundle_resource_dir:
            - %%dir%%/themes/%%current_theme%%/%%bundle_name%%/%%template%%
            - %%dir%%/themes/2013s1/%%bundle_name%%/%%template%%

muneris:
    host: http://muneris.bellcom.dk/
ax:
    wsdl: ""

# @see https://github.com/KnpLabs/KnpSnappyBundle
knp_snappy:
    pdf:
        enabled:    true
        binary:     %wkhtmltopdf_bin%
    image:
        enabled:    false

account:
    consignor:
        installation_id: 90290000026

consignor:
    shipment_server: ~
    ship_advisor:    ~

bazinga_js_translation:
    locale_fallback: %locale%
    default_domain: js

leezy_pheanstalk:
    enabled: true
    pheanstalks:
        primary:
            server: %beanstalkd.server%
            default: true
