# please note, do NOT split this section - it will break the application
# the security section MUST be defined in one place, and cannot be overwritten
security:
    firewalls:
        kernel_global:
            pattern: ^/da_DK/retarteging/order-feed/
            anonymous: ~
            http_basic:
                realm: "Secured Area"
                provider: in_memory

        secured_area:
            pattern: .*
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
            logout:
                path:   logout
                target: _homepage
                invalidate_session: true
                success_handler: hanzo.logout_success_handler
            provider: main

    access_control:
        - { path: ^/fx/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

        - { path: ^/.*/account/password-forgotten, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/.*/account/create, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/.*/account/check/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/.*/account/nno, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

        - { path: ^/.*/account, roles: ROLE_USER, requires_channel: https }
        - { path: ^/.*/checkout, roles: ROLE_USER, requires_channel: https }

        - { path: ^/.*/admin, roles: ROLE_EMPLOYEE }
        - { path: ^/.*/retarteging/order-feed/, roles: ROLE_KG_API_USER, requires_channel: https }

    providers:
        main:
            propel:
                class: Hanzo\Model\Customers
                property: email
        in_memory:
            memory:
                users:
                    # Kernel Global api access user.
                    # Here to allow access to: ^/da_DK/retarteging/order-feed/*
                    kg_api:
                        password: "KG1s0=s1_aw0z"
                        roles:    ROLE_KG_API_USER

    encoders:
        Hanzo\Model\Customers:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false
        Symfony\Component\Security\Core\User\User: plaintext

    access_decision_manager:
            strategy: unanimous
