# please note, do NOT split this section - it will break the application
# the security section MUST be defined in one place, and cannot be overwritten
security:
    firewalls:
        secured_area:
            pattern: .*
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
            logout:
                path:   logout
                target: _homepage
                invalidate_session: true
                success_handler: hanzo.logout_success_handler
                handlers:
                    - nelmio_security.flexible_ssl_listener

    access_control:
        - { path: ^/fx/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

        - { path: ^/.*/account/password-forgotten, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/.*/account/create, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/.*/account/check/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/.*/account/nno, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }

        - { path: ^/.*/account, roles: ROLE_USER }
        - { path: ^/.*/checkout, roles: ROLE_USER }

        - { path: ^/.*/admin, roles: ROLE_EMPLOYEE }

    providers:
        main:
            propel:
                class: Hanzo\Model\Customers
                property: email

    encoders:
        Hanzo\Model\Customers:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false

    access_decision_manager:
            strategy: unanimous
