# please note, do NOT split this section - it will break the application
# the security section MUST be defined in one place, and cannot be overwritten
security:
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        kernel_global:
            pattern: ^/da_DK/retarteging/order-feed/
            anonymous: ~
            http_basic:
                realm: "Secured Area"
                provider: in_memory

        secured_area:
            pattern: .*
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
            logout:
                path:   logout
                target: _homepage
                invalidate_session: true
                success_handler: hanzo.logout_success_handler
            provider: main

    access_control:
        account_login:
            path: login
            roles: IS_AUTHENTICATED_ANONYMOUSLY
            requires_channel: https
        account_password_forgotten:
            path: ^/[a-z]{2}_[A-Z]{2}/account/password-forgotten
            roles: IS_AUTHENTICATED_ANONYMOUSLY
            requires_channel: https
        account_create:
            path: ^/[a-z]{2}_[A-Z]{2}/account/create
            roles: IS_AUTHENTICATED_ANONYMOUSLY
            requires_channel: https
        account_check:
            path: ^/[a-z]{2}_[A-Z]{2}/account/check/
            roles: IS_AUTHENTICATED_ANONYMOUSLY
            requires_channel: https
        account_nno:
            path: ^/[a-z]{2}_[A-Z]{2}/account/nno
            roles: IS_AUTHENTICATED_ANONYMOUSLY
            requires_channel: https
        admin_login:
            path: admin_login
            roles: IS_AUTHENTICATED_ANONYMOUSLY
            requires_channel: https


        account:
            path: ^/[a-z]{2}_[A-Z]{2}/account
            roles: ROLE_USER
            requires_channel: https
        checkout:
            path: ^/[a-z]{2}_[A-Z]{2}/checkout
            roles: ROLE_USER
            requires_channel: https

        admin:
            path: ^/[a-z]{2}_[A-Z]{2}/admin
            roles: ROLE_EMPLOYEE
        retarteting:
            path: ^/[a-z]{2}_[A-Z]{2}/retarteging/order-feed/
            roles: ROLE_KG_API_USER
            requires_channel: https

    providers:
        main:
            propel:
                class: Hanzo\Model\Customers
                property: email
        in_memory:
            memory:
                users:
                    # Kernel Global api access user.
                    # Here to allow access to: ^/da_DK/retarteging/order-feed/*
                    kg_api:
                        password: "KG1s0=s1_aw0z....NO-ACCESS"
                        roles:    ROLE_KG_API_USER

    encoders:
        Hanzo\Model\Customers:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false
        Symfony\Component\Security\Core\User\User: plaintext

    access_decision_manager:
            strategy: unanimous
