Boy.png:
    Navy:
        - Navy
        - White
        - Blue
        - Wine
        - Red
        - Blue Denim
        - Black
        - Camel
        - Yellow
        - Grey
        - Sand
        - Grey Melange
        - Black
        - White
    Brown:
        - Brown
        - Sand
        - Grey Melange
        - Grey
        - Khaki
        - White
        - Blue Denim
        - Black
    Green:
        - Green
        - Blue Denim
        - Navy
        - Khaki
        - Sand
        - White
        - Black
        - Camel
    Grey:
        - Grey Melange
        - Grey
        - Blue Denim
        - Khaki
        - Sand
        - Black
        - White
        - Off White
        - Wine
        - Camel
        - Blue
Girl.png:
    Violet:
        - Violet
        - Khaki
        - Grey Melange
        - Blue Denim
        - Grey
        - Violet Melange
        - Violet/Grey
        - Black
        - Sand
        - White
        - Dusty Rose
        - Light Violet
        - Coffee
    Grey:
        - Grey Melange
        - Grey
        - Dark Grey Melange
        - Blue Denim
        - Light Grey Melange
        - Curry
        - Black
        - White
        - Violet/Grey
        - Sand
        - Off White
    Brown:
        - Khaki
        - Brown Melange
        - Brown/Curry
        - Brown
        - White
        - Sand
        - Coffee
        - Curry
        - Blue Denim
        - Black
    Peach/Blue:
        - Peach
        - Sand
        - Blue Denim
        - White
        - Grey Melange
        - Blue/Coral
        - Coffee
        - Blue
        - Navy
        - Light Grey Melange
        - Dark Grey Melange
