
AdminBundle:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

DataIOBundle:
    resource: "@DataIOBundle/Resources/config/routing.yml"
    prefix:   /

ShippingBundle:
    resource: "@ShippingBundle/Resources/config/routing.yml"
    prefix:   /

ServiceBundle:
    resource: "@ServiceBundle/Resources/config/routing.yml"
    prefix:   /

CheckoutBundle:
    resource: "@CheckoutBundle/Resources/config/routing.yml"
    prefix:   /

AccountBundle:
    resource: "@AccountBundle/Resources/config/routing.yml"
    prefix:   /

NewsletterBundle:
    resource: "@NewsletterBundle/Resources/config/routing.yml"
    prefix:   /

PaymentBundle:
    resource: "@PaymentBundle/Resources/config/routing.yml"
    prefix:   /

BasketBundle:
    resource: "@BasketBundle/Resources/config/routing.yml"
    prefix:   /

HanzoSearchBundle:
    resource: "@HanzoSearchBundle/Resources/config/routing.yml"
    prefix:   /

HanzoProductBundle:
    resource: "@HanzoProductBundle/Resources/config/routing.yml"
    prefix:   /

HanzoMannequinBundle:
    resource: "@HanzoMannequinBundle/Resources/config/routing.yml"
    prefix:   /

HanzoCategoryBundle:
    resource: "@HanzoCategoryBundle/Resources/config/routing.yml"
    prefix:   /

WebServicesBundle:
    resource: "@WebServicesBundle/Resources/config/routing.yml"
    prefix:   /

HanzoCMSBundle:
    resource: "@HanzoCMSBundle/Resources/config/routing.yml"
    prefix:   /

HanzoCMSBundle_cms:
    resource: "@HanzoCMSBundle/Resources/config/cms_routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
