EventsBundle:
    resource: "@EventsBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

WallBundle:
    resource: "@WallBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

AdminBundle:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

DataIOBundle:
    resource: "@DataIOBundle/Resources/config/routing.yml"
    prefix:   /

ShippingBundle:
    resource: "@ShippingBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

ServiceBundle:
    resource: "@ServiceBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

CheckoutBundle:
    resource: "@CheckoutBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

AccountBundle:
    resource: "@AccountBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

NewsletterBundle:
    resource: "@NewsletterBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

PaymentBundle:
    resource: "@PaymentBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

BasketBundle:
    resource: "@BasketBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

HanzoSearchBundle:
    resource: "@HanzoSearchBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

HanzoProductBundle:
    resource: "@HanzoProductBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

HanzoMannequinBundle:
    resource: "@HanzoMannequinBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

HanzoCategoryBundle:
    resource: "@HanzoCategoryBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

WebServicesBundle:
    resource: "@WebServicesBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

HanzoCMSBundle:
    resource: "@HanzoCMSBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

HanzoCMSBundle_cms_dyn:
    resource: .
    type: cms

# note we rewrote this to acommodate the locale neded in the start of the url
# _bazinga_exposetranslation:
#     resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"
bazinga_exposetranslation_js:
    pattern:  /{_locale}/i18n/{domain_name}.{_format}
    defaults: { _controller: bazinga.exposetranslation.controller:exposeTranslationAction, domain_name: "messages", _format: "js" }
    requirements:
        _format: js


_splash:
    pattern:  /
    defaults: { _controller: HanzoCMSBundle:Default:splash }


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
