WallBundle:
    resource: "@WallBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/


AdminBundle:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

DataIOBundle:
    resource: "@DataIOBundle/Resources/config/routing.yml"
    prefix:   /

ShippingBundle:
    resource: "@ShippingBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

ServiceBundle:
    resource: "@ServiceBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

CheckoutBundle:
    resource: "@CheckoutBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

AccountBundle:
    resource: "@AccountBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

NewsletterBundle:
    resource: "@NewsletterBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

PaymentBundle:
    resource: "@PaymentBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

BasketBundle:
    resource: "@BasketBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

HanzoSearchBundle:
    resource: "@HanzoSearchBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

HanzoProductBundle:
    resource: "@HanzoProductBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

HanzoMannequinBundle:
    resource: "@HanzoMannequinBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

HanzoCategoryBundle:
    resource: "@HanzoCategoryBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

WebServicesBundle:
    resource: "@WebServicesBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

HanzoCMSBundle:
    resource: "@HanzoCMSBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

HanzoCMSBundle_cms_dyn:
    resource: .
    type: cms

_bazinga_exposetranslation:
    resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"
    prefix:   /

_splash:
    pattern:  /
    defaults: { _controller: HanzoCMSBundle:Default:splash }


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
