security:
    firewalls:
        secured_area:
            pattern: .*
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                path:   /logout
                target: /
                invalidate_session: true
    access_control:
        - { path: ^/account/create, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/checkout, roles: ROLE_USER }
        - { path: ^/account, roles: ROLE_USER }
    providers:
        custom_provider:
            id: hanzo.account.security.provider
    encoders:
        Hanzo\Bundle\AccountBundle\Security\User\ProxyUser:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false
