parameters:
    ax.ecommerce.services.class: Hanzo\Bundle\AxBundle\Actions\In\Soap\ECommerceServices\ECommerceServices
    ax.out.service.class: Hanzo\Bundle\AxBundle\Actions\Out\AxService

services:
    # don't change naming format - the controller needs this
    ax.ECommerceServices.service:
        class: %ax.ecommerce.services.class%
        arguments:
            - @request
            - @logger
            - @hanzo.external_service.logger
            - @event_dispatcher
            - @hanzo.propel_replicator
        scope: request
    ax.out:
        class: %ax.out.service.class%
        arguments:
            - %ax.wsdl%
            - %ax.log_requests%
            - @logger
            - @hanzo.external_service.logger
            - @event_dispatcher
            - @translator

    ax.out.checkout.listener:
        class: Hanzo\Bundle\AxBundle\Event\CheckoutListener
        arguments:
            - @ax.out
            - @logger
#            - @hanzo.external_service.logger
        tags:
            - { name: kernel.event_listener, event: order.payment.collected, method: onPaymentCollected, priority: 0 }
