_homepage:
    pattern:  /
    defaults: { _controller: CMSBundle:Default:index }

view_page:
    pattern:  /page/view/{id}
    defaults:
        _controller: CMSBundle:Default:view
        page: null
    requirements:
        id: \d+
