basket_add:
    pattern:  /add-to-basket
    defaults: { _controller: BasketBundle:Default:add, _format: json }
    requirements: { _format: (xml|json), _method: POST }

basket_remove:
    pattern:  /remove-from-basket/{product_id}/{quantity}
    defaults:
        _controller: BasketBundle:Default:remove
        _format: rest
        quantity: all
        product_id: 0
    requirements:
        _format: html|json
        product_id: \d+
        quantity: \d+|all

basket_update:
    pattern:  /update-basket
    defaults:
        _controller: BasketBundle:Default:update
        _format: rest
    requirements:
        _format: html|json

basket_view:
    pattern:  /basket
    defaults: { _controller: BasketBundle:Default:view }

basket_view_mini:
    pattern:  /miniBasket
    defaults: { _controller: BasketBundle:Default:miniBasket }
