parameters:
    hanzo.basket.class: Hanzo\Bundle\BasketBundle\Service\Basket

services:
    hanzo.basket:
        class: %hanzo.basket.class%
        arguments:
            stock: @stock
            eventDispatcher: @event_dispatcher
            securityContext: @security.context
