parameters:
    hanzo_location_locator.class: Hanzo\Bundle\LocationLocatorBundle\LocationLocator

services:
    hanzo_location_locator:
        class: %hanzo_location_locator.class%
        arguments: [%postnord_api_key%, @translator]
