rma_form:
    pattern:  /account/order/{order_id}/rma
    defaults:
        _controller: RMABundle:Default:form
    requirements:
        order_id: \d+

rma_get:
    pattern:  /account/order/{order_id}/rma/get/{pdf}
    defaults:
        _controller: RMABundle:Default:get
        pdf: NULL

rma_upload_complete:
    pattern: /rma/upload
    defaults: { _controller: RMABundle:Default:uploadComplete, _format: json }
    requirements: { _format: json, _method: POST }
