gift_card_form:
    pattern: /checkout/gift-card/apply
    defaults:
        _controller: DiscountBundle:GiftCard:applyGiftCard

coupon_form:
    pattern: /checkout/coupon/apply
    defaults:
        _controller: DiscountBundle:Coupon:apply

