parameters:
#    hanzo_mannequin.example.class: Hanzo\Bundle\MannequinBundle\Example

services:
#    hanzo_mannequin.example:
#        class: %hanzo_mannequin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
