parameters:
    redis.class: Hanzo\Bundle\RedisBundle\Client\Redis
    redis.logger.class: Hanzo\Bundle\RedisBundle\Logger\Logger
    redis.data_collector.class: Hanzo\Bundle\RedisBundle\DataCollector\RedisDataCollector

services:
    redis:
       class: %redis.class%
    redis.logger:
        class: %redis.logger.class%
        arguments: [@logger]
    redis.data_collector:
        class: %redis.data_collector.class%
        tags:
            - { name: data_collector, template: 'RedisBundle:Collector:redis', id: redis }
        arguments: [@redis.logger]
