parameters:
#    hanzo_search.example.class: Hanzo\Bundle\SearchBundle\Example

services:
#    hanzo_search.example:
#        class: %hanzo_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
