parameters:
    hanzo_search.product.index_builder.class: Hanzo\Bundle\SearchBundle\ProductIndexBuilder

services:
    hanzo_search.product.index_builder:
        class: %hanzo_search.product.index_builder.class%
