cms:
    frontpage: 538

framework:
    default_locale: de_AT
    session:
        cookie_path: '/de_AT'

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:               %database_driver%
                user:                 %prod_at_database_user%
                password:             %prod_at_database_password%
                dsn:                  mysql:host=%prod_at_database_host%;dbname=%prod_at_database_name%
                options:              {}
                attributes:           {}
