cms:
    frontpage: 538

framework:
    default_locale: de_AT
    session:
        cookie_path: '/de_AT'

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:               %database_driver%
                user:                 %prod_at_database_user%
                password:             %prod_at_database_password%
                dsn:                  mysql:host=%prod_at_database_host%;dbname=%prod_at_database_name%
                options:              {}
                attributes:           {}

consignor:
    shipment_server:
        options:
              actor: 206
              product_concept_id: 94
              service_id: ""
              key: PDLAT
              to_address:
                  name: "POMPdeLUX De GmbH"
                  address_line_1: "Dammtorstraße 12"
                  postal_code: "20354"
                  city: "Hamburg Ust-IdNr."
                  country_iso2: DE
                  email: mailde@pompdelux.com
                  phone: "040-3571 5072"

google:
    analytics_code:    UA-1793665-9
    conversion_id:     976104979
    site_verification:
        - "idm5dDOLlFrLJl2npZ8fgvE3j0a_OlYPK3O-j37DxLI"
        - "XQd3QHxI9Xa9d5d-ExR5LZEz6JO9--7l1d9LAhwnGcg" # Heinrich
        - "SBOj-_vTXS3T6HczLxCmAwi-cAn5h1OrIuz_c5DmK8M" # Katrine
