cms:
    frontpage: 538

framework:
    default_locale: de_CH
    session:
        cookie_path: '/de_CH'

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:               %database_driver%
                user:                 %prod_ch_database_user%
                password:             %prod_ch_database_password%
                dsn:                  mysql:host=%prod_ch_database_host%;dbname=%prod_ch_database_name%
                options:              {}
                attributes:           {}

consignor:
    shipment_server:
        options:
            actor: 205
            product_concept_id: 1961
            service_id: ""
            key: PDLCH
            to_address:
                name: "POMPdeLUX Aps"
                address_line_1: "Postfach"
                postal_code: "9024"
                city: "St. Gallen"
                country_iso2: CH
                email: mailch@pompdelux.com
                phone: "044 201 33 33"

google:
    google_tag_manager_id: "GTM-5HKLX5"
    analytics_code: ~
    conversion_id:     972329147
    site_verification:
        - "3fafy3BakvvcWFWLva7D16MtGZfhuqfx5Bt32sjGms4"
        - "QSPLT5CPgnZKHXMZ_UlD0FnCBB0VeyCuQT3uV9YW2_s" # Heinrich
        - "Ge0BAo7GXDHJnjyKgUAwDITI6qgHiUflWHeWSWHUZUs" # Katrine
