framework:
    default_locale: en_GB
    session:
        cookie_path: '/en_GB'

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:               %database_driver%
                user:                 %prod_dk_database_user%
                password:             %prod_dk_database_password%
                dsn:                  mysql:host=%prod_dk_database_host%;dbname=%prod_dk_database_name%
                options:              {}
                attributes:           {}

account:
    consignor:
        actor_id: 63

consignor:
    shipment_server: ~

google:
    site_verification:
        - "pHWJ1LeG5mq3mITyz1TcTCpCpdNA72sr-UJ6cElk6B0"
        - "3t8Aa9P5lTTfUpxHcKkfIdsanDXc6xUQ3e5m9TUrF3M" #katrine
    tag_manager:
        gtm_id: "GTM-KTKM5M"
        enabled_datalayers:
            - Ecommerce
