cms:
    frontpage: 89
    twig:
        left_menu:
            type: main
            from: 10
        sub_menu:
            type: sub
            from: 400
            offset: 482

google:
    tag_manager:
        gtm_id: "GTM-KV65DG"
        enabled_datalayers:
            - Ecommerce
