cms:
    frontpage: 538

framework:
    default_locale: de_DE
    session:
        cookie_path: '/de_DE'

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:               %database_driver%
                user:                 %prod_de_database_user%
                password:             %prod_de_database_password%
                dsn:                  mysql:host=%prod_de_database_host%;dbname=%prod_de_database_name%
                options:              {}
                attributes:           {}

account:
    consignor:
        actor_id: 69

consignor:
    shipment_server:
        options:
              actor: 147
              product_concept_id: 1765
              service_id: ""
              key: PompDeluxDE
              to_address:
                  name: "POMPdeLUX De GmbH"
                  address_line_1: "Dammtorstraße 12"
                  postal_code: "20354"
                  city: "Hamburg Ust-IdNr."
                  country_iso2: DE
                  email: mailde@pompdelux.com
                  phone: "040-3571 5072"
