cms:
    frontpage: 538

framework:
    default_locale: de_DE
    session:
        cookie_path: '/de_DE'

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:               %database_driver%
                user:                 %prod_de_database_user%
                password:             %prod_de_database_password%
                dsn:                  mysql:host=%prod_de_database_host%;dbname=%prod_de_database_name%
                options:              {}
                attributes:           {}

account:
    consignor:
        actor_id: 69

consignor:
    shipment_server:
        options:
            actor: 147
            product_concept_id: 1765
            service_id: ""
            key: PompDeluxDE
            to_address:
                name: "POMPdeLUX"
                address_line_1: "Krokamp 128"
                postal_code: "24539"
                city: "Neumünster"
                country_iso2: DE
                email: mailde@pompdelux.com
                phone: "040-3571 5072"

google:
    site_verification:
        - "URU_P3h0jo598hqu49Bc-wB7PKEUg9rNRFJTdF7w1fg"
        - "fcjM6pv4RppzbiCcV-A1zGuLF8OnMKbmfeB8RIUnLqA" # Heinrich
        - "taoGTV73AZz7EsPr0ZkbE70HERE12nSM1z8PCx7pIog" # Katrine
    tag_manager:
        gtm_id: "GTM-M3DZCT"
        enabled_datalayers:
            - Ecommerce
