cms:
    frontpage: 538

framework:
    default_locale: fi_FI
    session:
        cookie_path: '/fi_FI'

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:               %database_driver%
                user:                 %prod_fi_database_user%
                password:             %prod_fi_database_password%
                dsn:                  mysql:host=%prod_fi_database_host%;dbname=%prod_fi_database_name%
                options:              {}
                attributes:           {}
                # slaves:
                #     pdldbdk2:
                #         user:         %database_slave_1_user%
                #         password:     %database_slave_1_password%
                #         dsn:          %database_slave_1_dsn%
                #     pdldbdk3:
                #         user:         %database_slave_2_user%
                #         password:     %database_slave_2_password%
                #         dsn:          %database_slave_2_dsn%
                #     pdldbdk4:
                #         user:         %database_slave_3_user%
                #         password:     %database_slave_3_password%
                #         dsn:          %database_slave_3_dsn%

account:
    consignor:
        actor_id: 68

consignor:
    shipment_server:
        options:
              actor: 6201
              product_concept_id: 94
              service_id: 9024
              key: PompDeluxFI
              to_address:
                  name: "POMPdeLUX ApS"
                  address_line_1: "Møgelhøj 8"
                  postal_code: "8520"
                  city: "Lystrup"
                  country_iso2: DK
                  email: mailfi@pompdelux.com
                  phone: "09-34870870"
