cms:
    frontpage: 538

framework:
    default_locale: fi_FI
    session:
        cookie_path: '/fi_FI'

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:               %database_driver%
                user:                 %prod_fi_database_user%
                password:             %prod_fi_database_password%
                dsn:                  mysql:host=%prod_fi_database_host%;dbname=%prod_fi_database_name%
                options:              {}
                attributes:           {}

account:
    consignor:
        actor_id: 68

consignor:
    shipment_server:
        options:
            actor: 144
            product_concept_id: 560
            service_id: ""
            key: PompDeluxFI
            to_address:
                name: "POMPdeLUX"
                address_line_1: "PL 6530"
                postal_code: "00002"
                city: "Helsinki"
                country_iso2: FI
                email: mailfi@pompdelux.com
                phone: "09-34870870"

google:
    google_tag_manager_id: "GTM-NT4PP4"
    conversion_id:     976104979
    site_verification:
        - "AXKJxgYZdJP9NLgDW1isf5JEH3PoTUxLK6vdNWHB8po"
        - "Mn5pB5AND0OzgYGC7XXbZy_aeTpdl6A6WtyJN6d1ROE" # katrine
