framework:
    default_locale: nl_NL
    session:
        cookie_path: '/nl_NL'

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:               %database_driver%
                user:                 %prod_nl_database_user%
                password:             %prod_nl_database_password%
                dsn:                  mysql:host=%prod_nl_database_host%;dbname=%prod_nl_database_name%
                options:              {}
                attributes:           {}

account:
    consignor:
        actor_id: 67

consignor:
    shipment_server: ~

google:
    analytics_code:    UA-1793665-5
    conversion_id:     976104979
    site_verification: "OPkXRDSUZqEJM56eo2rk4tApaxiQUjQjHcoXGOk_EIU"
