cms:
    frontpage: 538

framework:
    default_locale: nb_NO
    session:
        cookie_path: '/nb_NO'

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:               %database_driver%
                user:                 %prod_no_database_user%
                password:             %prod_no_database_password%
                dsn:                  mysql:host=%prod_no_database_host%;dbname=%prod_no_database_name%
                options:              {}
                attributes:           {}

account:
    consignor:
        actor_id: 66

consignor:
    shipment_server:
        options:
              actor: 142
              product_concept_id: 560
              service_id: ""
              key: PompDeluxNO
              to_address:
                  name: "POMPdeLUX c/o Tollpost"
                  address_line_1: "Globe Postens Godssenter"
                  postal_code: "0668"
                  city: "Oslo"
                  country_iso2: NO
                  email: mail@pompdelux.no
                  phone: "+47 22742600"

google:
    analytics_code:    UA-1793665-4
    conversion_id:     976104979
    site_verification:
        - "idm5dDOLlFrLJl2npZ8fgvE3j0a_OlYPK3O-j37DxLI"
        - "MzH0LJSf9bE8-ncQFmMzVFGPXWyOWBO67b94i96RMoI"
        - "cQ7rHU7in1iEG6iAVBzIuOH4fdSxfN1akYbz1HaQZCA" # katrine
    addwords:
        conversion:
            id: 972268397
            label: o5jOCKOstwgQ7cbOzwM
