cms:
    frontpage: 538

framework:
    default_locale: nb_NO
    session:
        cookie_path: '/nb_NO'

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:               %database_driver%
                user:                 %prod_no_database_user%
                password:             %prod_no_database_password%
                dsn:                  mysql:host=%prod_no_database_host%;dbname=%prod_no_database_name%
                options:              {}
                attributes:           {}
                # slaves:
                #     pdldbdk2:
                #         user:         %database_slave_1_user%
                #         password:     %database_slave_1_password%
                #         dsn:          %database_slave_1_dsn%
                #     pdldbdk3:
                #         user:         %database_slave_2_user%
                #         password:     %database_slave_2_password%
                #         dsn:          %database_slave_2_dsn%
                #     pdldbdk4:
                #         user:         %database_slave_3_user%
                #         password:     %database_slave_3_password%
                #         dsn:          %database_slave_3_dsn%

account:
    consignor:
        actor_id: 66

consignor:
    shipment_server:
        options:
              actor: 142
              product_concept_id: 560
              service_id: ""
              key: PompDeluxNO
              to_address:
                  name: "POMPdeLUX c/o Tollpost"
                  address_line_1: "Globe Postens Godssenter"
                  postal_code: "0668"
                  city: "Oslo"
                  country_iso2: NO
                  email: mail@pompdelux.no
                  phone: "+47 22742600"
