monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
            channels: [ "!3ps" ]
        nested:
            type:         stream
            path:         %kernel.logs_dir%/%kernel.environment%.log
            level:        debug
            channels:     [ "!3ps" ]
        third_party_services:
            type:     stream
            path:     %kernel.logs_dir%/%kernel.environment%.log
            level:    info
            channels: [ "3ps" ]

framework:
    trusted_proxies: [ %proxy_ip% ]
    trusted_hosts:   [ '.*?\.?pompdelux.com' ]
    templating:
        assets_base_urls:
            http: [ "%assets_base_url%" ]
            ssl:  [ "%assets_base_url%" ]

varnish:
    host:   %varnish_host%
    port:   %varnish_port%
    secret: %varnish_secret%

ax:
    wsdl: "http://193.89.255.250:8000/DynamicsAxServices.asmx?wsdl"

consignor:
    shipment_server:
        endpoint: "https://www.shipmentserver.com/ship/ShipmentServerModule.dll"
