_checkout:
    pattern:  /checkout
    defaults: { _controller: CheckoutBundle:Default:index }

CheckoutBundle_state:
    pattern:  /checkout/state
    defaults: { _controller: CheckoutBundle:Default:state, _format: json }
    requirements: { _format: (xml|json), _method: POST }

CheckoutBundle_validate:
    pattern:  /checkout/validate
    defaults: { _controller: CheckoutBundle:Default:validate, _format: json }
    requirements: { _format: (xml|json), _method: POST }

CheckoutBundle_update:
    pattern:  /checkout/update/{block}/{state}
    defaults: { _controller: CheckoutBundle:Default:update, _format: json }
    requirements: { _format: (xml|json), _method: POST }

CheckoutBundle_summery:
    pattern:  /checkout/summery
    defaults: { _controller: CheckoutBundle:Default:summery }

_checkout_success:
    pattern:  /checkout/success
    defaults: { _controller: CheckoutBundle:Default:success }

_checkout_failed:
    pattern:  /checkout/failed
    defaults: { _controller: CheckoutBundle:Default:failed }

_checkout_populate_order:
    pattern:  /checkout/populate_order
    defaults: { _controller: CheckoutBundle:Default:populateOrder, _format: json }
    requirements: { _format: (xml|json), _method: POST }
