parameters:
#    checkout.example.class: Hanzo\Bundle\CheckoutBundle\Example

services:
    hanzo.checkout:
        class: Hanzo\Bundle\CheckoutBundle\Event\CheckoutListener
        arguments: [ @mail_manager, @ax_manager, @translator, @session ]
        tags:
            - { name: kernel.event_listener, event: order.payment.collected, method: onPaymentCollected }
            - { name: kernel.event_listener, event: order.payment.failed, method: onPaymentFailed }

    hanzo.order:
        class: Hanzo\Bundle\CheckoutBundle\Event\OrderListener
        arguments: [ @session, @ax_manager ]
        tags:
            - { name: kernel.event_listener, event: order.edit.start, method: onEditStart }
            - { name: kernel.event_listener, event: order.edit.cancel, method: onEditCancel }
            - { name: kernel.event_listener, event: order.edit.done, method: onEditDone }
