parameters:
#    checkout.example.class: Hanzo\Bundle\CheckoutBundle\Example

services:
    hanzo.checkout.checkout.listener:
        class: Hanzo\Bundle\CheckoutBundle\Event\CheckoutListener
        arguments:
            session:       @session
            payment_proxy: @payment.actions.proxy
        tags:
            - { name: kernel.event_listener, event: order.payment.collected, method: onPaymentCollectedFirst, priority: 255 }
            - { name: kernel.event_listener, event: order.payment.collected, method: onPaymentCollected, priority: -255 }
            - { name: kernel.event_listener, event: order.payment.failed, method: onPaymentFailed }
            - { name: kernel.event_listener, event: order.summery.finalize, method: onFinalize, priority: 20 }

    hanzo.order:
        class: Hanzo\Bundle\CheckoutBundle\Event\OrderListener
        arguments:
            session:         @session
            service_wrapper: @ax.out.service.wrapper
        tags:
            - { name: kernel.event_listener, event: order.edit.start, method: onEditStart }
            - { name: kernel.event_listener, event: order.edit.cancel, method: onEditCancel }
            - { name: kernel.event_listener, event: order.edit.done, method: onEditDone }

    hanzo.order.send.confirmation.mail:
        class: Hanzo\Bundle\CheckoutBundle\SendOrderConfirmationMail
        arguments:
            translator:        @translator
            mail_manager:      @mail_manager
            address_formatter: @hanzo.address_formatter
