parameters:
#    checkout.example.class: Hanzo\Bundle\CheckoutBundle\Example

services:
    hanzo.checkout.checkout.listener:
        class: Hanzo\Bundle\CheckoutBundle\Event\CheckoutListener
        arguments: [ @mail_manager, @ax.out, @translator, @session ]
        tags:
            - { name: kernel.event_listener, event: order.payment.collected, method: onPaymentCollected, priority: 0 }
            - { name: kernel.event_listener, event: order.payment.failed, method: onPaymentFailed }
            - { name: kernel.event_listener, event: order.summery.finalize, method: onFinalize, priority: 20 }

    hanzo.order:
        class: Hanzo\Bundle\CheckoutBundle\Event\OrderListener
        arguments: [ @session, @ax.out ]
        tags:
            - { name: kernel.event_listener, event: order.edit.start, method: onEditStart }
            - { name: kernel.event_listener, event: order.edit.cancel, method: onEditCancel }
            - { name: kernel.event_listener, event: order.edit.done, method: onEditDone }
