parameters:
    varnish.controle.class: Hanzo\Bundle\VarnishBundle\varnish

services:
    varnish.controle:
        class: %varnish.controle.class%
        arguments: [%varnish.host%, %varnish.port%, %varnish.secret%, %varnish.timeout%]
