parameters:
    varnish.controle.class: Hanzo\Bundle\VarnishBundle\Varnish

services:
    varnish.controle:
        class: %varnish.controle.class%
        arguments: [%varnish.host%, %varnish.port%, %varnish.secret%, %varnish.timeout%]

    varnish.controle.ban.listener:
        class: Hanzo\Bundle\VarnishBundle\Event\BanListener
        arguments: [ @varnish.controle, @router, %kernel.cache_dir%, @translator ]
        tags:
            - { name: kernel.event_listener, event: cms.node.deleted, method: onBanCmsNode }
            - { name: kernel.event_listener, event: cms.node.updated, method: onBanCmsNode }
            - { name: kernel.event_listener, event: category.node.deleted, method: onCategoryDeleteNode }
            - { name: kernel.event_listener, event: category.product_sort.update, method: onCategoryDeleteNode }
            - { name: kernel.event_listener, event: product.stock.zero, method: onProductSoldOut }
