wall:
    pattern:  /wall
    defaults: { _controller: WallBundle:Default:index }

get_wall:
    pattern: /wall/get-wall/{pager}
    defaults:
        _controller: WallBundle:Default:getWall
        pager: 0
    requirements:
        pager: \d+

edit_entry:
    pattern: /wall/edit-entry/{id}
    defaults:
        _controller: WallBundle:Default:editEntry
    requirements:
        id: \d+

add_entry:
    pattern: /wall/add-entry
    defaults:
        _controller: WallBundle:Default:addEntry
        id: null

add_comment:
    pattern: /wall/add-comment/{id}
    defaults:
        _controller: WallBundle:Default:addEntry
    requirements:
        id: \d+