parameters:
    service_factory.class: Hanzo\Bundle\ServiceBundle\ServiceFactory

    mail_manager.class: Hanzo\Bundle\ServiceBundle\Services\MailService
    sms_manager.class: Hanzo\Bundle\ServiceBundle\Services\SmsService
    twig_string.class: Hanzo\Bundle\ServiceBundle\Services\TwigStringService
    cache_manager.class: Hanzo\Bundle\ServiceBundle\Services\CacheService

services:
    service_factory:
        class:           %service_factory.class%

    mail_manager:
        class:           %mail_manager.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     mail
            parameters:  [@mailer, @twig_string]
            class:       %mail_manager.class%

    sms_manager:
        class:           %sms_manager.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     sms
            parameters:  ~
            class:       %sms_manager.class%

    twig_string:
        class:           %twig_string.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     mail
            parameters:  [@twig]
            class:       %twig_string.class%

    cache_manager:
        class:           %cache_manager.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     cache
            parameters:  [@snc_redis.default_client]
            class:       %cache_manager.class%
