parameters:
    service_factory.class: Hanzo\Bundle\ServiceBundle\ServiceFactory

    mail_manager.class: Hanzo\Bundle\ServiceBundle\Services\MailService
    sms_manager.class: Hanzo\Bundle\ServiceBundle\Services\SmsService
    twig_string.class: Hanzo\Bundle\ServiceBundle\Services\TwigStringService
    cache_manager.class: Hanzo\Bundle\ServiceBundle\Services\CacheService
    cleanup_manager.class: Hanzo\Bundle\ServiceBundle\Services\CleanupService
    ax_manager.class: Hanzo\Bundle\ServiceBundle\Services\AxService
    geoip_manager.class: Hanzo\Bundle\ServiceBundle\Services\GeoIPService
    replication_manager.class: Hanzo\Bundle\ServiceBundle\Services\ReplicationService

services:
    service_factory:
        class:           %service_factory.class%

    mail_manager:
        class:           %mail_manager.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     mail
            parameters:  [@mailer, @twig_string]
            class:       %mail_manager.class%

    sms_manager:
        class:           %sms_manager.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     sms
            parameters:  ~
            class:       %sms_manager.class%

    twig_string:
        class:           %twig_string.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     twig_string
            parameters:  [@twig]
            class:       %twig_string.class%

    cache_manager:
        class:           %cache_manager.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     cache
            parameters:  [@snc_redis.default_client]
            class:       %cache_manager.class%

    cleanup_manager:
        class:           %cleanup_manager.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     cleanup
            parameters:  [@payment.dibsapi]
            class:       %cleanup_manager.class%

    ax_manager:
        class:           %ax_manager.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     ax
            parameters:  [@logger]
            class:       %ax_manager.class%

    geoip_manager:
        class:           %geoip_manager.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     geoip
            parameters:  [@request]
            class:       %geoip_manager.class%
        scope: request

    replication_manager:
        class:           %replication_manager.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     replication
            parameters:  [@propel.configuration]
            class:       %replication_manager.class%
