_newsletter_action:
    pattern:  /newsletter/{action}
    defaults: { _controller: NewsletterBundle:Default:handle, _format: json }
    requirements: { _format: (xml|json), _method: POST }

_newsletter_account_action:
    pattern:  /account/newsletter
    defaults: { _controller: NewsletterBundle:Default:allLists }

_newsletter_subscribe:
    pattern:  /newsletter/subscribe/current
    defaults: { _controller: NewsletterBundle:Default:subscribe }
