parameters:
    newsletterapi.class: Hanzo\Bundle\NewsletterBundle\NewsletterApi
#    newsletterprovider.class: Hanzo\Bundle\NewsletterBundle\Providers\MailPlatformProvider
    newsletterprovider.class: Hanzo\Bundle\NewsletterBundle\Providers\MailChimpProvider

services:
    newsletterapi:
        class: %newsletterapi.class%
        arguments: [@mail_manager, @newsletterprovider, @pdl.phpredis.main]
    newsletterprovider:
        class: %newsletterprovider.class%
        arguments: [%core.domain_key%]