parameters:
#    hanzo_newsletter.example.class: Hanzo\Bundle\NewsletterBundle\Example

services:
#    hanzo_newsletter.example:
#        class: %hanzo_newsletter.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
