parameters:
#    newsletter.example.class: Hanzo\Bundle\NewsletterBundle\Example

services:
#    newsletter.example:
#        class: %newsletter.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
