parameters:
    newsletterapi.class: Hanzo\Bundle\NewsletterBundle\NewsletterApi
    newsletterprovider.class: Hanzo\Bundle\NewsletterBundle\Providers\MailPlatformProvider

services:
    newsletterapi:
        class: %newsletterapi.class%
        arguments: [@mail_manager, @newsletterprovider, @pdl.phpredis.main]
    newsletterprovider:
        class: %newsletterprovider.class%
