DataIOBundle_update_system:
    pattern: /update-system/
    defaults: { _controller: DataIOBundle:Default:updateSystem }
    requirements: { _format: (xml|json), _method: POST }

_session_migrate_test:
    pattern: /test-migrate/{step}
    defaults: { _controller: DataIOBundle:Default:testMigrate }

_order_test:
    pattern: /test-order/{state}
    defaults: { _controller: DataIOBundle:Default:testOrder }

_pc_check:
    pattern: /pc-test
    defaults: { _controller: DataIOBundle:Default:check }

_varnish_ping:
    pattern: /varnish-ping
    defaults: { _controller: DataIOBundle:Default:ping }

_error_500:
    pattern: /error/500/{method}
    defaults:
        _controller: DataIOBundle:Default:error500
        method: 1
