DataIOBundle_update_system:
    pattern: /update-system/
    defaults: { _controller: DataIOBundle:Default:updateSystem }
    requirements: { _format: (xml|json), _method: POST }

_session_migrate_test:
    pattern: /test-migrate/{step}
    defaults: { _controller: DataIOBundle:Default:testMigrate }

_order_test:
    pattern: /test-order/{state}
    defaults: { _controller: DataIOBundle:Default:testOrder }
