parameters:
    data_io.update.class: Hanzo\Bundle\DataIOBundle\UpdateListener

services:
    data_io.update_listener:
        class: %data_io.update.class%
        tags:
            - { name: kernel.event_listener, event: hanzo.update.incrementAssetsVersion, method: onIncrementAssetsVersion }
    data_io.update_listener:
        class: %data_io.update.class%
        tags:
            - { name: kernel.event_listener, event: hanzo.update.updateTranslations, method: onUpdateTranslations}
