parameters:
#    data_io.example.class: Hanzo\Bundle\DataIOBundle\Example

services:
    data_io.update_listener:
        class: Hanzo\Bundle\DataIOBundle\UpdateListener
        tags:
            - { name: kernel.event_listener, event: hanzo.update.incrementAssetsVersion, method: onIncrementAssetsVersion }
