product_info:
    pattern:    /product/view/{product_id}
    defaults:
        _controller: HanzoProductBundle:Default:view
        product_id: 1
    requirements:
        product_id: \d+

product_set:
    pattern:    /product/bundle/{image_id}
    defaults:
        _controller: HanzoProductBundle:Bundle:view
        image_id: 1
    requirements:
        image_id: \d+

product_custom_set:
    pattern:    /product/bundle/set/{set}
    defaults:
        _controller: HanzoProductBundle:Bundle:custom
        set: 1
