parameters:
#    product.example.class: Hanzo\Bundle\ProductBundle\Example

services:
#    product.example:
#        class: %product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
