parameters:
#    hanzo_product.example.class: Hanzo\Bundle\ProductBundle\Example

services:
#    hanzo_product.example:
#        class: %hanzo_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
