parameters:
    hanzo_product.range.class: Hanzo\Bundle\ProductBundle\Range
    hanzo_product.range.twig.extension.class: Hanzo\Bundle\ProductBundle\Twig\Extension\RangeExtension

services:
    hanzo_product.range:
        class: %hanzo_product.range.class%
        arguments:
            - @session
            - %core.active_product_range%

    hanzo_product.range.twig.extension:
        class: %hanzo_product.range.twig.extension.class%
        arguments:
            - @hanzo_product.range
        tags:
            -   { name: twig.extension }
